package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"

	"flightdeck/internal/auth"
)

// runUp bootstraps a self-contained flightdeck instance: an instance directory
// with a generated .env (secrets, created once and never overwritten) and a
// docker-compose.yml (regenerated each run — all variables live in .env), then
// `docker compose up -d --build`. Idempotent: re-running against an existing
// instance just re-applies the compose. This is how a second instance (e.g. a
// work laptop) runs without touching any shared infra: its own postgres, its
// own redis, bound to 127.0.0.1 only.
func runUp(args []string) {
	fs := flag.NewFlagSet("up", flag.ExitOnError)
	dir := fs.String("dir", "", "instance directory (default ~/.flightdeck/<name>)")
	name := fs.String("name", "", "instance/compose project name (default: basename of --dir, else \"work\")")
	port := fs.Int("port", 4300, "host port to bind on 127.0.0.1")
	repo := fs.String("repo", "", "path to the flightdeck repo checkout (build context; default: current directory)")
	noStart := fs.Bool("no-start", false, "generate files only, don't run docker compose")
	_ = fs.Parse(args)

	repoDir := *repo
	if repoDir == "" {
		repoDir = "."
	}
	repoAbs, err := filepath.Abs(repoDir)
	if err != nil {
		log.Fatalf("resolve repo path: %v", err)
	}
	if _, err := os.Stat(filepath.Join(repoAbs, "Dockerfile")); err != nil {
		log.Fatalf("%s does not look like the flightdeck repo (no Dockerfile) — pass --repo", repoAbs)
	}

	instName := *name
	if instName == "" {
		if *dir != "" {
			instName = filepath.Base(*dir)
		} else {
			instName = "work"
		}
	}
	instDir := *dir
	if instDir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			log.Fatalf("home dir: %v", err)
		}
		instDir = filepath.Join(home, ".flightdeck", instName)
	}
	instAbs, err := filepath.Abs(instDir)
	if err != nil {
		log.Fatalf("resolve instance dir: %v", err)
	}

	for _, d := range []string{instAbs, filepath.Join(instAbs, "pgdata"), filepath.Join(instAbs, "backups")} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			log.Fatalf("mkdir %s: %v", d, err)
		}
	}

	// .env holds the secrets; write once, never overwrite, so re-running up
	// can't rotate the DB password or setup token out from under the instance.
	envPath := filepath.Join(instAbs, ".env")
	var setupToken string
	if _, err := os.Stat(envPath); os.IsNotExist(err) {
		pgPass, err := auth.NewRawKey("")
		if err != nil {
			log.Fatalf("rand: %v", err)
		}
		setupToken, err = auth.NewRawKey("fdsetup_")
		if err != nil {
			log.Fatalf("rand: %v", err)
		}
		env := fmt.Sprintf(`# Generated by "flightdeck up" — secrets for this instance. Not overwritten on re-run.
FLIGHTDECK_PORT=%d
POSTGRES_PASSWORD=%s
FLIGHTDECK_SETUP_TOKEN=%s
# Optional: enables semantic search (can also be set later in the web UI).
OPENAI_API_KEY=
`, *port, pgPass, setupToken)
		if err := os.WriteFile(envPath, []byte(env), 0o600); err != nil {
			log.Fatalf("write .env: %v", err)
		}
	} else if err != nil {
		log.Fatalf("stat .env: %v", err)
	}

	composePath := filepath.Join(instAbs, "docker-compose.yml")
	var buf bytes.Buffer
	tpl := template.Must(template.New("compose").Parse(composeTemplate))
	if err := tpl.Execute(&buf, map[string]string{"Repo": repoAbs}); err != nil {
		log.Fatalf("render compose: %v", err)
	}
	if err := os.WriteFile(composePath, buf.Bytes(), 0o644); err != nil {
		log.Fatalf("write compose: %v", err)
	}

	fmt.Printf("instance %q ready in %s\n", instName, instAbs)
	if *noStart {
		fmt.Println("skipping start (--no-start); run:")
		fmt.Printf("  docker compose -p %s --project-directory %s up -d --build\n", instName, instAbs)
		return
	}

	cmd := exec.Command("docker", "compose", "-p", instName, "--project-directory", instAbs, "up", "-d", "--build")
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatalf("docker compose up: %v", err)
	}

	fmt.Printf("\nflightdeck %q is starting:\n", instName)
	fmt.Printf("  UI / API : http://127.0.0.1:%d\n", *port)
	fmt.Printf("  MCP      : http://127.0.0.1:%d/mcp\n", *port)
	if setupToken != "" {
		fmt.Println("\n  SETUP TOKEN (first run — paste into the web UI wizard):")
		fmt.Printf("    %s\n", setupToken)
	} else {
		fmt.Printf("\n  setup token (if setup is still pending): see %s\n", envPath)
	}
}

// composeTemplate is the self-contained instance stack. Everything variable
// lives in the sibling .env; the file itself is regenerated on every up run.
const composeTemplate = `# Generated by "flightdeck up" — regenerated on every run; edit .env instead.
services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: flightdeck
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flightdeck"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  flightdeck:
    build: {{.Repo}}
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/flightdeck?sslmode=disable
      FLIGHTDECK_REDIS_URL: redis://redis:6379/2
      FLIGHTDECK_SETUP_TOKEN: ${FLIGHTDECK_SETUP_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "127.0.0.1:${FLIGHTDECK_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
`
