// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_semantic.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	pgvec "flightdeck/internal/pgvec"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertActivityEmbedding = `-- name: InsertActivityEmbedding :exec
INSERT INTO activity_embeddings (activity_id, embedding, model)
VALUES ($1, $2::vector, $3::text)
ON CONFLICT (activity_id) DO UPDATE SET embedding = EXCLUDED.embedding, model = EXCLUDED.model
`

type InsertActivityEmbeddingParams struct {
	ActivityID uuid.UUID    `json:"activity_id"`
	Embedding  pgvec.Vector `json:"embedding"`
	Model      string       `json:"model"`
}

// Upsert so marking a row 'failed' and later embedding it (or vice versa in a
// race) never errors.
func (q *Queries) InsertActivityEmbedding(ctx context.Context, arg InsertActivityEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertActivityEmbedding, arg.ActivityID, arg.Embedding, arg.Model)
	return err
}

const listActivityNeedingEmbedding = `-- name: ListActivityNeedingEmbedding :many
SELECT a.id, a.body
FROM activity a
LEFT JOIN activity_embeddings e ON e.activity_id = a.id
WHERE a.kind IN ('decision', 'progress', 'rejected')
  AND a.body <> ''
  AND e.activity_id IS NULL
ORDER BY a.created_at DESC
LIMIT $1::int
`

type ListActivityNeedingEmbeddingRow struct {
	ID   uuid.UUID `json:"id"`
	Body string    `json:"body"`
}

// High-signal activity (decisions, progress, rejections — the "why" agents
// search for) that has no embedding yet. Rows with a 'failed' marker are poison
// and skipped. Activity is immutable, so there is no re-embed-on-edit path.
func (q *Queries) ListActivityNeedingEmbedding(ctx context.Context, lim int32) ([]ListActivityNeedingEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, listActivityNeedingEmbedding, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityNeedingEmbeddingRow
	for rows.Next() {
		var i ListActivityNeedingEmbeddingRow
		if err := rows.Scan(&i.ID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchActivitySemantic = `-- name: SearchActivitySemantic :many
SELECT a.id, a.project_id, a.item_id, a.kind, a.actor, a.body, a.metadata,
       a.confidence, a.created_at,
       (e.embedding <=> $1::vector) AS distance
FROM activity a
JOIN activity_embeddings e ON e.activity_id = a.id
WHERE e.embedding IS NOT NULL
  AND ($2::uuid IS NULL OR a.project_id = $2)
  AND (e.embedding <=> $1::vector) < $3::float8
ORDER BY e.embedding <=> $1::vector
LIMIT COALESCE($4::int, 25)
`

type SearchActivitySemanticParams struct {
	QueryEmbedding pgvec.Vector `json:"query_embedding"`
	ProjectID      pgtype.UUID  `json:"project_id"`
	MaxDistance    float64      `json:"max_distance"`
	Lim            *int32       `json:"lim"`
}

type SearchActivitySemanticRow struct {
	ID         uuid.UUID       `json:"id"`
	ProjectID  uuid.UUID       `json:"project_id"`
	ItemID     pgtype.UUID     `json:"item_id"`
	Kind       string          `json:"kind"`
	Actor      string          `json:"actor"`
	Body       string          `json:"body"`
	Metadata   json.RawMessage `json:"metadata"`
	Confidence string          `json:"confidence"`
	CreatedAt  time.Time       `json:"created_at"`
	Distance   interface{}     `json:"distance"`
}

// Approximate nearest-neighbour search over decision/progress bodies by cosine
// distance, bounded by max_distance like the item variant.
func (q *Queries) SearchActivitySemantic(ctx context.Context, arg SearchActivitySemanticParams) ([]SearchActivitySemanticRow, error) {
	rows, err := q.db.Query(ctx, searchActivitySemantic,
		arg.QueryEmbedding,
		arg.ProjectID,
		arg.MaxDistance,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchActivitySemanticRow
	for rows.Next() {
		var i SearchActivitySemanticRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ItemID,
			&i.Kind,
			&i.Actor,
			&i.Body,
			&i.Metadata,
			&i.Confidence,
			&i.CreatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
