// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activity (project_id, item_id, kind, actor, body, metadata, confidence)
VALUES (
    $1,
    $2,
    COALESCE($3::text, 'comment'),
    COALESCE($4::text, ''),
    COALESCE($5::text, ''),
    COALESCE($6::jsonb, '{}'),
    COALESCE($7::text, 'unspecified')
)
RETURNING id, project_id, item_id, kind, actor, body, metadata, created_at, search, confidence
`

type CreateActivityParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	ItemID     pgtype.UUID `json:"item_id"`
	Kind       *string     `json:"kind"`
	Actor      *string     `json:"actor"`
	Body       *string     `json:"body"`
	Metadata   []byte      `json:"metadata"`
	Confidence *string     `json:"confidence"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.ProjectID,
		arg.ItemID,
		arg.Kind,
		arg.Actor,
		arg.Body,
		arg.Metadata,
		arg.Confidence,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ItemID,
		&i.Kind,
		&i.Actor,
		&i.Body,
		&i.Metadata,
		&i.CreatedAt,
		&i.Search,
		&i.Confidence,
	)
	return i, err
}

const listActivity = `-- name: ListActivity :many
SELECT id, project_id, item_id, kind, actor, body, metadata, created_at, search, confidence FROM activity
WHERE ($1::uuid IS NULL OR project_id = $1)
  AND ($2::uuid IS NULL OR item_id = $2)
  AND ($3::text IS NULL OR kind = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
ORDER BY created_at DESC
LIMIT COALESCE($5::int, 200)
`

type ListActivityParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ItemID    pgtype.UUID `json:"item_id"`
	Kind      *string     `json:"kind"`
	Since     *time.Time  `json:"since"`
	Lim       *int32      `json:"lim"`
}

func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivity,
		arg.ProjectID,
		arg.ItemID,
		arg.Kind,
		arg.Since,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ItemID,
			&i.Kind,
			&i.Actor,
			&i.Body,
			&i.Metadata,
			&i.CreatedAt,
			&i.Search,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivityByProject = `-- name: ListRecentActivityByProject :many
SELECT id, project_id, item_id, kind, actor, body, metadata, created_at, search, confidence FROM activity
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentActivityByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListRecentActivityByProject(ctx context.Context, arg ListRecentActivityByProjectParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listRecentActivityByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ItemID,
			&i.Kind,
			&i.Actor,
			&i.Body,
			&i.Metadata,
			&i.CreatedAt,
			&i.Search,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDecisionsByProject = `-- name: ListRecentDecisionsByProject :many
SELECT id, project_id, item_id, kind, actor, body, metadata, created_at, search, confidence FROM activity
WHERE project_id = $1 AND kind IN ('decision', 'status_change')
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentDecisionsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListRecentDecisionsByProject(ctx context.Context, arg ListRecentDecisionsByProjectParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listRecentDecisionsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ItemID,
			&i.Kind,
			&i.Actor,
			&i.Body,
			&i.Metadata,
			&i.CreatedAt,
			&i.Search,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchActivity = `-- name: SearchActivity :many
SELECT a.id, a.project_id, a.item_id, a.kind, a.actor, a.body, a.metadata, a.created_at, a.search, a.confidence, ts_rank(a.search, plainto_tsquery('english', $1)) AS rank
FROM activity a
WHERE a.search @@ plainto_tsquery('english', $1)
  AND ($2::uuid IS NULL OR a.project_id = $2)
ORDER BY rank DESC
LIMIT COALESCE($3::int, 50)
`

type SearchActivityParams struct {
	Q         string      `json:"q"`
	ProjectID pgtype.UUID `json:"project_id"`
	Lim       *int32      `json:"lim"`
}

type SearchActivityRow struct {
	ID         uuid.UUID       `json:"id"`
	ProjectID  uuid.UUID       `json:"project_id"`
	ItemID     pgtype.UUID     `json:"item_id"`
	Kind       string          `json:"kind"`
	Actor      string          `json:"actor"`
	Body       string          `json:"body"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  time.Time       `json:"created_at"`
	Search     interface{}     `json:"search"`
	Confidence string          `json:"confidence"`
	Rank       float32         `json:"rank"`
}

func (q *Queries) SearchActivity(ctx context.Context, arg SearchActivityParams) ([]SearchActivityRow, error) {
	rows, err := q.db.Query(ctx, searchActivity, arg.Q, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchActivityRow
	for rows.Next() {
		var i SearchActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ItemID,
			&i.Kind,
			&i.Actor,
			&i.Body,
			&i.Metadata,
			&i.CreatedAt,
			&i.Search,
			&i.Confidence,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
