// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	pgvec "flightdeck/internal/pgvec"
	"github.com/google/uuid"
)

const activityKindCountsSince = `-- name: ActivityKindCountsSince :many
SELECT kind, count(*) AS n
FROM activity
WHERE project_id = $1 AND created_at >= $2
GROUP BY kind
`

type ActivityKindCountsSinceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ActivityKindCountsSinceRow struct {
	Kind string `json:"kind"`
	N    int64  `json:"n"`
}

func (q *Queries) ActivityKindCountsSince(ctx context.Context, arg ActivityKindCountsSinceParams) ([]ActivityKindCountsSinceRow, error) {
	rows, err := q.db.Query(ctx, activityKindCountsSince, arg.ProjectID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityKindCountsSinceRow
	for rows.Next() {
		var i ActivityKindCountsSinceRow
		if err := rows.Scan(&i.Kind, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDistinctItemsTouchedSince = `-- name: CountDistinctItemsTouchedSince :one
SELECT count(DISTINCT item_id) AS n
FROM activity
WHERE project_id = $1 AND created_at >= $2 AND item_id IS NOT NULL
`

type CountDistinctItemsTouchedSinceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CountDistinctItemsTouchedSince(ctx context.Context, arg CountDistinctItemsTouchedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDistinctItemsTouchedSince, arg.ProjectID, arg.CreatedAt)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const listStaleInProgress = `-- name: ListStaleInProgress :many
SELECT i.id, i.project_id, i.type, i.title, i.body, i.status, i.priority, i.assignee, i.position, i.source, i.external_ref, i.tags, i.metadata, i.created_at, i.updated_at, i.closed_at, i.deleted_at, i.search, i.idempotency_key, i.acceptance_criteria, i.seq, i.ref, i.version, i.embedding, i.embedding_model, p.slug AS project_slug
FROM items i
JOIN projects p ON p.id = i.project_id AND p.status = 'active'
WHERE i.deleted_at IS NULL AND i.status = 'in_progress' AND i.updated_at < $1
ORDER BY i.updated_at ASC
`

type ListStaleInProgressRow struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee"`
	Position           float64         `json:"position"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	Tags               []string        `json:"tags"`
	Metadata           json.RawMessage `json:"metadata"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           *time.Time      `json:"closed_at"`
	DeletedAt          *time.Time      `json:"deleted_at"`
	Search             interface{}     `json:"search"`
	IdempotencyKey     *string         `json:"idempotency_key"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria"`
	Seq                int64           `json:"seq"`
	Ref                string          `json:"ref"`
	Version            int32           `json:"version"`
	Embedding          pgvec.Vector    `json:"embedding"`
	EmbeddingModel     string          `json:"embedding_model"`
	ProjectSlug        string          `json:"project_slug"`
}

// in_progress items whose last update is older than the cutoff.
func (q *Queries) ListStaleInProgress(ctx context.Context, updatedAt time.Time) ([]ListStaleInProgressRow, error) {
	rows, err := q.db.Query(ctx, listStaleInProgress, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleInProgressRow
	for rows.Next() {
		var i ListStaleInProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleProjectSummaries = `-- name: ListStaleProjectSummaries :many
SELECT p.id, p.slug, p.name, p.status, p.summary, p.repo_url, p.site_url, p.created_at, p.updated_at, p.instructions, p.item_seq, p.aliases, p.parent_slug, max(a.created_at)::timestamptz AS last_activity
FROM projects p
JOIN activity a ON a.project_id = p.id
WHERE p.status = 'active'
GROUP BY p.id
HAVING max(a.created_at) > p.updated_at + interval '1 hour'
ORDER BY max(a.created_at) DESC
`

type ListStaleProjectSummariesRow struct {
	ID           uuid.UUID `json:"id"`
	Slug         string    `json:"slug"`
	Name         string    `json:"name"`
	Status       string    `json:"status"`
	Summary      string    `json:"summary"`
	RepoUrl      *string   `json:"repo_url"`
	SiteUrl      *string   `json:"site_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Instructions string    `json:"instructions"`
	ItemSeq      int64     `json:"item_seq"`
	Aliases      []string  `json:"aliases"`
	ParentSlug   *string   `json:"parent_slug"`
	LastActivity time.Time `json:"last_activity"`
}

// active projects whose latest activity is newer than the last summary refresh.
func (q *Queries) ListStaleProjectSummaries(ctx context.Context) ([]ListStaleProjectSummariesRow, error) {
	rows, err := q.db.Query(ctx, listStaleProjectSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleProjectSummariesRow
	for rows.Next() {
		var i ListStaleProjectSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Summary,
			&i.RepoUrl,
			&i.SiteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Instructions,
			&i.ItemSeq,
			&i.Aliases,
			&i.ParentSlug,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUntriagedBugs = `-- name: ListUntriagedBugs :many
SELECT i.id, i.project_id, i.type, i.title, i.body, i.status, i.priority, i.assignee, i.position, i.source, i.external_ref, i.tags, i.metadata, i.created_at, i.updated_at, i.closed_at, i.deleted_at, i.search, i.idempotency_key, i.acceptance_criteria, i.seq, i.ref, i.version, i.embedding, i.embedding_model, p.slug AS project_slug
FROM items i
JOIN projects p ON p.id = i.project_id AND p.status = 'active'
WHERE i.deleted_at IS NULL AND i.type = 'bug' AND i.status = 'backlog' AND i.created_at < $1
ORDER BY i.created_at ASC
`

type ListUntriagedBugsRow struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee"`
	Position           float64         `json:"position"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	Tags               []string        `json:"tags"`
	Metadata           json.RawMessage `json:"metadata"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           *time.Time      `json:"closed_at"`
	DeletedAt          *time.Time      `json:"deleted_at"`
	Search             interface{}     `json:"search"`
	IdempotencyKey     *string         `json:"idempotency_key"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria"`
	Seq                int64           `json:"seq"`
	Ref                string          `json:"ref"`
	Version            int32           `json:"version"`
	Embedding          pgvec.Vector    `json:"embedding"`
	EmbeddingModel     string          `json:"embedding_model"`
	ProjectSlug        string          `json:"project_slug"`
}

// bugs still sitting in backlog (never triaged) older than the cutoff.
func (q *Queries) ListUntriagedBugs(ctx context.Context, createdAt time.Time) ([]ListUntriagedBugsRow, error) {
	rows, err := q.db.Query(ctx, listUntriagedBugs, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUntriagedBugsRow
	for rows.Next() {
		var i ListUntriagedBugsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
