// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveAPIKeys = `-- name: CountActiveAPIKeys :one
SELECT count(*) FROM api_keys WHERE revoked = false
`

func (q *Queries) CountActiveAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, key_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, key_hash, scopes, created_at, last_used_at, revoked, expires_at
`

type CreateAPIKeyParams struct {
	Name      string     `json:"name"`
	KeyHash   string     `json:"key_hash"`
	Scopes    []string   `json:"scopes"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.KeyHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, key_hash, scopes, created_at, last_used_at, revoked, expires_at FROM api_keys
WHERE key_hash = $1 AND revoked = false
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, scopes, created_at, last_used_at, revoked FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	Revoked    bool       `json:"revoked"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys SET revoked = true WHERE id = $1
RETURNING id, name, scopes, created_at, last_used_at, revoked
`

type RevokeAPIKeyRow struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	Revoked    bool       `json:"revoked"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) (RevokeAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, id)
	var i RevokeAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
	)
	return i, err
}

const rotateAPIKey = `-- name: RotateAPIKey :one
UPDATE api_keys SET key_hash = $2, revoked = false, expires_at = NULL, last_used_at = NULL
WHERE id = $1
RETURNING id, name, scopes, created_at, last_used_at, revoked
`

type RotateAPIKeyParams struct {
	ID      uuid.UUID `json:"id"`
	KeyHash string    `json:"key_hash"`
}

type RotateAPIKeyRow struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	Revoked    bool       `json:"revoked"`
}

// Replace a key's secret in place (same id/name/scopes), clearing revoked/expiry.
func (q *Queries) RotateAPIKey(ctx context.Context, arg RotateAPIKeyParams) (RotateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, rotateAPIKey, arg.ID, arg.KeyHash)
	var i RotateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
