// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countAttachmentsForItem = `-- name: CountAttachmentsForItem :one
SELECT count(*) FROM attachments WHERE item_id = $1
`

func (q *Queries) CountAttachmentsForItem(ctx context.Context, itemID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachmentsForItem, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (item_id, filename, content_type, size_bytes, object_key, actor)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, item_id, filename, content_type, size_bytes, object_key, actor, created_at
`

type CreateAttachmentParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	ObjectKey   string    `json:"object_key"`
	Actor       string    `json:"actor"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ItemID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.ObjectKey,
		arg.Actor,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ObjectKey,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :one
DELETE FROM attachments WHERE id = $1 RETURNING id, item_id, filename, content_type, size_bytes, object_key, actor, created_at
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, deleteAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ObjectKey,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, item_id, filename, content_type, size_bytes, object_key, actor, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ObjectKey,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsForItem = `-- name: ListAttachmentsForItem :many
SELECT id, item_id, filename, content_type, size_bytes, object_key, actor, created_at FROM attachments WHERE item_id = $1 ORDER BY created_at
`

func (q *Queries) ListAttachmentsForItem(ctx context.Context, itemID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.ObjectKey,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
