// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_impact.sql

package store

import (
	"context"
	"time"
)

const contextEffectivenessSummary = `-- name: ContextEffectivenessSummary :one
WITH sessions AS (
    SELECT
        actor,
        session_id,
        bool_or(effect = 'helpful') AS helpful,
        bool_or(effect = 'neutral') AS neutral,
        bool_or(effect = 'harmful') AS harmful,
        bool_or(mechanism = 'prevented_error') AS prevented_error,
        bool_or(mechanism = 'duplicate_work_avoided') AS duplicate_work_avoided,
        sum(COALESCE(estimated_minutes_delta, 0)) AS estimated_minutes_net
    FROM context_impact_events
    WHERE recorded_at >= $1
    GROUP BY actor, session_id
)
SELECT
    count(*) AS reported_sessions,
    count(*) FILTER (WHERE helpful) AS helpful_sessions,
    count(*) FILTER (WHERE neutral) AS neutral_sessions,
    count(*) FILTER (WHERE harmful) AS harmful_sessions,
    count(*) FILTER (WHERE prevented_error) AS prevented_error_sessions,
    count(*) FILTER (WHERE duplicate_work_avoided) AS duplicate_work_avoided_sessions,
    COALESCE(sum(estimated_minutes_net), 0)::bigint AS estimated_minutes_net
FROM sessions
`

type ContextEffectivenessSummaryRow struct {
	ReportedSessions             int64 `json:"reported_sessions"`
	HelpfulSessions              int64 `json:"helpful_sessions"`
	NeutralSessions              int64 `json:"neutral_sessions"`
	HarmfulSessions              int64 `json:"harmful_sessions"`
	PreventedErrorSessions       int64 `json:"prevented_error_sessions"`
	DuplicateWorkAvoidedSessions int64 `json:"duplicate_work_avoided_sessions"`
	EstimatedMinutesNet          int64 `json:"estimated_minutes_net"`
}

func (q *Queries) ContextEffectivenessSummary(ctx context.Context, recordedAt time.Time) (ContextEffectivenessSummaryRow, error) {
	row := q.db.QueryRow(ctx, contextEffectivenessSummary, recordedAt)
	var i ContextEffectivenessSummaryRow
	err := row.Scan(
		&i.ReportedSessions,
		&i.HelpfulSessions,
		&i.NeutralSessions,
		&i.HarmfulSessions,
		&i.PreventedErrorSessions,
		&i.DuplicateWorkAvoidedSessions,
		&i.EstimatedMinutesNet,
	)
	return i, err
}

const createContextImpactEvent = `-- name: CreateContextImpactEvent :one
INSERT INTO context_impact_events (
    actor,
    session_id,
    project,
    item,
    effect,
    mechanism,
    context_refs,
    evidence,
    estimated_minutes_delta,
    idempotency_key
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, recorded_at, actor, session_id, project, item, effect, mechanism, context_refs, evidence, estimated_minutes_delta, idempotency_key
`

type CreateContextImpactEventParams struct {
	Actor                 string   `json:"actor"`
	SessionID             string   `json:"session_id"`
	Project               string   `json:"project"`
	Item                  *string  `json:"item"`
	Effect                string   `json:"effect"`
	Mechanism             string   `json:"mechanism"`
	ContextRefs           []string `json:"context_refs"`
	Evidence              string   `json:"evidence"`
	EstimatedMinutesDelta *int32   `json:"estimated_minutes_delta"`
	IdempotencyKey        *string  `json:"idempotency_key"`
}

func (q *Queries) CreateContextImpactEvent(ctx context.Context, arg CreateContextImpactEventParams) (ContextImpactEvent, error) {
	row := q.db.QueryRow(ctx, createContextImpactEvent,
		arg.Actor,
		arg.SessionID,
		arg.Project,
		arg.Item,
		arg.Effect,
		arg.Mechanism,
		arg.ContextRefs,
		arg.Evidence,
		arg.EstimatedMinutesDelta,
		arg.IdempotencyKey,
	)
	var i ContextImpactEvent
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Actor,
		&i.SessionID,
		&i.Project,
		&i.Item,
		&i.Effect,
		&i.Mechanism,
		&i.ContextRefs,
		&i.Evidence,
		&i.EstimatedMinutesDelta,
		&i.IdempotencyKey,
	)
	return i, err
}

const getContextImpactByIdempotencyKey = `-- name: GetContextImpactByIdempotencyKey :one
SELECT id, recorded_at, actor, session_id, project, item, effect, mechanism, context_refs, evidence, estimated_minutes_delta, idempotency_key
FROM context_impact_events
WHERE actor = $1
  AND idempotency_key = $2
`

type GetContextImpactByIdempotencyKeyParams struct {
	Actor          string  `json:"actor"`
	IdempotencyKey *string `json:"idempotency_key"`
}

func (q *Queries) GetContextImpactByIdempotencyKey(ctx context.Context, arg GetContextImpactByIdempotencyKeyParams) (ContextImpactEvent, error) {
	row := q.db.QueryRow(ctx, getContextImpactByIdempotencyKey, arg.Actor, arg.IdempotencyKey)
	var i ContextImpactEvent
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Actor,
		&i.SessionID,
		&i.Project,
		&i.Item,
		&i.Effect,
		&i.Mechanism,
		&i.ContextRefs,
		&i.Evidence,
		&i.EstimatedMinutesDelta,
		&i.IdempotencyKey,
	)
	return i, err
}

const listContextImpactEvents = `-- name: ListContextImpactEvents :many
SELECT id, recorded_at, actor, session_id, project, item, effect, mechanism, context_refs, evidence, estimated_minutes_delta, idempotency_key
FROM context_impact_events
WHERE recorded_at >= $1
  AND ($2::text IS NULL OR project = $2)
ORDER BY recorded_at DESC
LIMIT $3
`

type ListContextImpactEventsParams struct {
	RecordedAt time.Time `json:"recorded_at"`
	Project    *string   `json:"project"`
	Lim        int32     `json:"lim"`
}

func (q *Queries) ListContextImpactEvents(ctx context.Context, arg ListContextImpactEventsParams) ([]ContextImpactEvent, error) {
	rows, err := q.db.Query(ctx, listContextImpactEvents, arg.RecordedAt, arg.Project, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextImpactEvent
	for rows.Next() {
		var i ContextImpactEvent
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.Actor,
			&i.SessionID,
			&i.Project,
			&i.Item,
			&i.Effect,
			&i.Mechanism,
			&i.ContextRefs,
			&i.Evidence,
			&i.EstimatedMinutesDelta,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
