// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items_semantic.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	pgvec "flightdeck/internal/pgvec"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listItemsNeedingEmbedding = `-- name: ListItemsNeedingEmbedding :many
SELECT id, ref, title, body
FROM items
WHERE deleted_at IS NULL AND embedding IS NULL AND embedding_model <> 'failed'
ORDER BY updated_at DESC
LIMIT $1::int
`

type ListItemsNeedingEmbeddingRow struct {
	ID    uuid.UUID `json:"id"`
	Ref   string    `json:"ref"`
	Title string    `json:"title"`
	Body  string    `json:"body"`
}

// Live items whose embedding is missing (never embedded, or invalidated by a
// content edit). The background embedder drains this in batches. Rows marked
// embedding_model='failed' are poison (repeatedly rejected) and skipped so one
// bad item can't stall the whole backlog; a content edit clears the marker.
func (q *Queries) ListItemsNeedingEmbedding(ctx context.Context, lim int32) ([]ListItemsNeedingEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, listItemsNeedingEmbedding, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsNeedingEmbeddingRow
	for rows.Next() {
		var i ListItemsNeedingEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.Title,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markItemEmbeddingFailed = `-- name: MarkItemEmbeddingFailed :exec
UPDATE items SET embedding_model = 'failed'
WHERE id = $1 AND embedding IS NULL
`

// Park a poison item so the embedder stops retrying it. Guarded by the
// still-NULL check so a successful concurrent embed isn't clobbered.
func (q *Queries) MarkItemEmbeddingFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markItemEmbeddingFailed, id)
	return err
}

const searchItemsSemantic = `-- name: SearchItemsSemantic :many
SELECT i.id, i.project_id, i.type, i.title, i.body, i.status, i.priority, i.assignee, i.position, i.source, i.external_ref, i.tags, i.metadata, i.created_at, i.updated_at, i.closed_at, i.deleted_at, i.search, i.idempotency_key, i.acceptance_criteria, i.seq, i.ref, i.version, i.embedding, i.embedding_model, (i.embedding <=> $1::vector) AS distance
FROM items i
WHERE i.deleted_at IS NULL
  AND i.embedding IS NOT NULL
  AND ($2::uuid IS NULL OR i.project_id = $2)
  AND ($3::text IS NULL OR i.type = $3)
  AND (i.embedding <=> $1::vector) < $4::float8
ORDER BY i.embedding <=> $1::vector
LIMIT COALESCE($5::int, 25)
`

type SearchItemsSemanticParams struct {
	QueryEmbedding pgvec.Vector `json:"query_embedding"`
	ProjectID      pgtype.UUID  `json:"project_id"`
	Type           *string      `json:"type"`
	MaxDistance    float64      `json:"max_distance"`
	Lim            *int32       `json:"lim"`
}

type SearchItemsSemanticRow struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee"`
	Position           float64         `json:"position"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	Tags               []string        `json:"tags"`
	Metadata           json.RawMessage `json:"metadata"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           *time.Time      `json:"closed_at"`
	DeletedAt          *time.Time      `json:"deleted_at"`
	Search             interface{}     `json:"search"`
	IdempotencyKey     *string         `json:"idempotency_key"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria"`
	Seq                int64           `json:"seq"`
	Ref                string          `json:"ref"`
	Version            int32           `json:"version"`
	Embedding          pgvec.Vector    `json:"embedding"`
	EmbeddingModel     string          `json:"embedding_model"`
	Distance           interface{}     `json:"distance"`
}

// Approximate nearest-neighbour search by cosine distance. Only rows within
// max_distance are returned, so an off-topic query yields nothing (and the
// caller falls through to trigram) rather than surfacing the globally-closest
// but irrelevant items.
func (q *Queries) SearchItemsSemantic(ctx context.Context, arg SearchItemsSemanticParams) ([]SearchItemsSemanticRow, error) {
	rows, err := q.db.Query(ctx, searchItemsSemantic,
		arg.QueryEmbedding,
		arg.ProjectID,
		arg.Type,
		arg.MaxDistance,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchItemsSemanticRow
	for rows.Next() {
		var i SearchItemsSemanticRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemEmbedding = `-- name: SetItemEmbedding :exec
UPDATE items
SET embedding = $1::vector,
    embedding_model = $2::text
WHERE id = $3 AND embedding IS NULL
`

type SetItemEmbeddingParams struct {
	Embedding      pgvec.Vector `json:"embedding"`
	EmbeddingModel string       `json:"embedding_model"`
	ID             uuid.UUID    `json:"id"`
}

// Store an embedding, but only if the item's content hasn't changed since it was
// read for embedding (guarded by the still-NULL check) — so an edit that races
// the embedder isn't clobbered with a stale vector.
func (q *Queries) SetItemEmbedding(ctx context.Context, arg SetItemEmbeddingParams) error {
	_, err := q.db.Exec(ctx, setItemEmbedding, arg.Embedding, arg.EmbeddingModel, arg.ID)
	return err
}
