// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, idempotency_key, acceptance_criteria)
VALUES (
    $1,
    COALESCE($2::text, 'task'),
    $3,
    COALESCE($4::text, ''),
    COALESCE($5::text, 'backlog'),
    COALESCE($6::text, 'med'),
    $7,
    COALESCE($8::double precision, 0),
    COALESCE($9::text, 'manual'),
    $10,
    COALESCE($11::text[], '{}'),
    COALESCE($12::jsonb, '{}'),
    $13,
    COALESCE($14::jsonb, '[]')
)
RETURNING id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model
`

type CreateItemParams struct {
	ProjectID          uuid.UUID `json:"project_id"`
	Type               *string   `json:"type"`
	Title              string    `json:"title"`
	Body               *string   `json:"body"`
	Status             *string   `json:"status"`
	Priority           *string   `json:"priority"`
	Assignee           *string   `json:"assignee"`
	Position           *float64  `json:"position"`
	Source             *string   `json:"source"`
	ExternalRef        *string   `json:"external_ref"`
	Tags               []string  `json:"tags"`
	Metadata           []byte    `json:"metadata"`
	IdempotencyKey     *string   `json:"idempotency_key"`
	AcceptanceCriteria []byte    `json:"acceptance_criteria"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ProjectID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Position,
		arg.Source,
		arg.ExternalRef,
		arg.Tags,
		arg.Metadata,
		arg.IdempotencyKey,
		arg.AcceptanceCriteria,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.Source,
		&i.ExternalRef,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Search,
		&i.IdempotencyKey,
		&i.AcceptanceCriteria,
		&i.Seq,
		&i.Ref,
		&i.Version,
		&i.Embedding,
		&i.EmbeddingModel,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model FROM items WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.Source,
		&i.ExternalRef,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Search,
		&i.IdempotencyKey,
		&i.AcceptanceCriteria,
		&i.Seq,
		&i.Ref,
		&i.Version,
		&i.Embedding,
		&i.EmbeddingModel,
	)
	return i, err
}

const getItemByRef = `-- name: GetItemByRef :one
SELECT id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model FROM items WHERE lower(ref) = lower($1) AND deleted_at IS NULL
`

func (q *Queries) GetItemByRef(ctx context.Context, lower string) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByRef, lower)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.Source,
		&i.ExternalRef,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Search,
		&i.IdempotencyKey,
		&i.AcceptanceCriteria,
		&i.Seq,
		&i.Ref,
		&i.Version,
		&i.Embedding,
		&i.EmbeddingModel,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model FROM items
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR project_id = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR type = $3)
  AND ($4::text IS NULL OR assignee = $4)
  AND ($5::text IS NULL OR $5::text = ANY(tags))
  AND ($6::timestamptz IS NULL OR updated_at >= $6)
  AND ($7::text IS NULL OR search @@ plainto_tsquery('english', $7))
ORDER BY position ASC, created_at DESC
LIMIT COALESCE($9::int, 500)
OFFSET COALESCE($8::int, 0)
`

type ListItemsParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	Status       *string     `json:"status"`
	Type         *string     `json:"type"`
	Assignee     *string     `json:"assignee"`
	Tag          *string     `json:"tag"`
	UpdatedSince *time.Time  `json:"updated_since"`
	Q            *string     `json:"q"`
	Off          *int32      `json:"off"`
	Lim          *int32      `json:"lim"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.ProjectID,
		arg.Status,
		arg.Type,
		arg.Assignee,
		arg.Tag,
		arg.UpdatedSince,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenItemsByProject = `-- name: ListOpenItemsByProject :many
SELECT id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model FROM items
WHERE project_id = $1 AND deleted_at IS NULL AND status NOT IN ('done', 'wontfix')
ORDER BY
    CASE priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 WHEN 'med' THEN 2 ELSE 3 END,
    position ASC
LIMIT $2
`

type ListOpenItemsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListOpenItemsByProject(ctx context.Context, arg ListOpenItemsByProjectParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listOpenItemsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteItem = `-- name: SoftDeleteItem :one
UPDATE items SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model
`

func (q *Queries) SoftDeleteItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, softDeleteItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.Source,
		&i.ExternalRef,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Search,
		&i.IdempotencyKey,
		&i.AcceptanceCriteria,
		&i.Seq,
		&i.Ref,
		&i.Version,
		&i.Embedding,
		&i.EmbeddingModel,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE items SET
    title     = COALESCE($1::text, title),
    body      = COALESCE($2::text, body),
    type      = COALESCE($3::text, type),
    status    = COALESCE($4::text, status),
    priority  = COALESCE($5::text, priority),
    assignee  = COALESCE($6::text, assignee),
    position  = COALESCE($7::double precision, position),
    tags      = COALESCE($8::text[], tags),
    metadata  = COALESCE($9::jsonb, metadata),
    acceptance_criteria = COALESCE($10::jsonb, acceptance_criteria),
    closed_at = CASE
                    WHEN COALESCE($4::text, status) IN ('done', 'wontfix')
                        THEN COALESCE(closed_at, now())
                    ELSE NULL
                END,
    -- Invalidate the embedding when the searchable content changes; the
    -- background embedder will re-embed rows whose embedding is NULL. The model
    -- marker is reset too so a previously 'failed' (poison) row gets retried
    -- with its new content.
    embedding = CASE
                    WHEN $1::text IS NOT NULL OR $2::text IS NOT NULL
                        THEN NULL
                    ELSE embedding
                END,
    embedding_model = CASE
                    WHEN $1::text IS NOT NULL OR $2::text IS NOT NULL
                        THEN ''
                    ELSE embedding_model
                END,
    version    = version + 1,
    updated_at = now()
WHERE id = $11 AND deleted_at IS NULL
  AND ($12::int IS NULL OR version = $12)
RETURNING id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model
`

type UpdateItemParams struct {
	Title              *string   `json:"title"`
	Body               *string   `json:"body"`
	Type               *string   `json:"type"`
	Status             *string   `json:"status"`
	Priority           *string   `json:"priority"`
	Assignee           *string   `json:"assignee"`
	Position           *float64  `json:"position"`
	Tags               []string  `json:"tags"`
	Metadata           []byte    `json:"metadata"`
	AcceptanceCriteria []byte    `json:"acceptance_criteria"`
	ID                 uuid.UUID `json:"id"`
	ExpectedVersion    *int32    `json:"expected_version"`
}

// Bumps version on every write. When expected_version is supplied it acts as a
// compare-and-swap: a mismatch matches no row (caller maps that to a conflict).
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.Title,
		arg.Body,
		arg.Type,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Position,
		arg.Tags,
		arg.Metadata,
		arg.AcceptanceCriteria,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.Source,
		&i.ExternalRef,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Search,
		&i.IdempotencyKey,
		&i.AcceptanceCriteria,
		&i.Seq,
		&i.Ref,
		&i.Version,
		&i.Embedding,
		&i.EmbeddingModel,
	)
	return i, err
}
