// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items_search.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	pgvec "flightdeck/internal/pgvec"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listTopOpenItemsPerProject = `-- name: ListTopOpenItemsPerProject :many
SELECT id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model, project_slug, rn FROM (
    SELECT i.id, i.project_id, i.type, i.title, i.body, i.status, i.priority, i.assignee, i.position, i.source, i.external_ref, i.tags, i.metadata, i.created_at, i.updated_at, i.closed_at, i.deleted_at, i.search, i.idempotency_key, i.acceptance_criteria, i.seq, i.ref, i.version, i.embedding, i.embedding_model, p.slug AS project_slug,
           row_number() OVER (
               PARTITION BY i.project_id
               ORDER BY CASE i.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 WHEN 'med' THEN 2 ELSE 3 END,
                        i.position ASC
           ) AS rn
    FROM items i
    JOIN projects p ON p.id = i.project_id AND p.status = 'active'
    WHERE i.deleted_at IS NULL AND i.status NOT IN ('done', 'wontfix')
) s
WHERE s.rn <= $1::int
ORDER BY s.project_slug, s.rn
`

type ListTopOpenItemsPerProjectRow struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee"`
	Position           float64         `json:"position"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	Tags               []string        `json:"tags"`
	Metadata           json.RawMessage `json:"metadata"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           *time.Time      `json:"closed_at"`
	DeletedAt          *time.Time      `json:"deleted_at"`
	Search             interface{}     `json:"search"`
	IdempotencyKey     *string         `json:"idempotency_key"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria"`
	Seq                int64           `json:"seq"`
	Ref                string          `json:"ref"`
	Version            int32           `json:"version"`
	Embedding          pgvec.Vector    `json:"embedding"`
	EmbeddingModel     string          `json:"embedding_model"`
	ProjectSlug        string          `json:"project_slug"`
	Rn                 int64           `json:"rn"`
}

// Top-N open items for every active project in a single windowed query — replaces
// the per-project N+1 loop that built the global "load the map" view.
func (q *Queries) ListTopOpenItemsPerProject(ctx context.Context, perProject int32) ([]ListTopOpenItemsPerProjectRow, error) {
	rows, err := q.db.Query(ctx, listTopOpenItemsPerProject, perProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopOpenItemsPerProjectRow
	for rows.Next() {
		var i ListTopOpenItemsPerProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.ProjectSlug,
			&i.Rn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItems = `-- name: SearchItems :many
SELECT i.id, i.project_id, i.type, i.title, i.body, i.status, i.priority, i.assignee, i.position, i.source, i.external_ref, i.tags, i.metadata, i.created_at, i.updated_at, i.closed_at, i.deleted_at, i.search, i.idempotency_key, i.acceptance_criteria, i.seq, i.ref, i.version, i.embedding, i.embedding_model, ts_rank(i.search, plainto_tsquery('english', $1)) AS rank
FROM items i
WHERE i.deleted_at IS NULL
  AND i.search @@ plainto_tsquery('english', $1)
  AND ($2::uuid IS NULL OR i.project_id = $2)
  AND ($3::text IS NULL OR i.type = $3)
ORDER BY rank DESC
LIMIT COALESCE($4::int, 50)
`

type SearchItemsParams struct {
	Q         string      `json:"q"`
	ProjectID pgtype.UUID `json:"project_id"`
	Type      *string     `json:"type"`
	Lim       *int32      `json:"lim"`
}

type SearchItemsRow struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee"`
	Position           float64         `json:"position"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	Tags               []string        `json:"tags"`
	Metadata           json.RawMessage `json:"metadata"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           *time.Time      `json:"closed_at"`
	DeletedAt          *time.Time      `json:"deleted_at"`
	Search             interface{}     `json:"search"`
	IdempotencyKey     *string         `json:"idempotency_key"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria"`
	Seq                int64           `json:"seq"`
	Ref                string          `json:"ref"`
	Version            int32           `json:"version"`
	Embedding          pgvec.Vector    `json:"embedding"`
	EmbeddingModel     string          `json:"embedding_model"`
	Rank               float32         `json:"rank"`
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]SearchItemsRow, error) {
	rows, err := q.db.Query(ctx, searchItems,
		arg.Q,
		arg.ProjectID,
		arg.Type,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchItemsRow
	for rows.Next() {
		var i SearchItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemsFuzzy = `-- name: SearchItemsFuzzy :many
SELECT i.id, i.project_id, i.type, i.title, i.body, i.status, i.priority, i.assignee, i.position, i.source, i.external_ref, i.tags, i.metadata, i.created_at, i.updated_at, i.closed_at, i.deleted_at, i.search, i.idempotency_key, i.acceptance_criteria, i.seq, i.ref, i.version, i.embedding, i.embedding_model, greatest(similarity(i.title, $1), similarity(i.ref, $1)) AS sim
FROM items i
WHERE i.deleted_at IS NULL
  AND (i.title % $1 OR i.ref % $1 OR i.title ILIKE '%' || $1 || '%')
  AND ($2::uuid IS NULL OR i.project_id = $2)
  AND ($3::text IS NULL OR i.type = $3)
ORDER BY sim DESC
LIMIT COALESCE($4::int, 25)
`

type SearchItemsFuzzyParams struct {
	Q         string      `json:"q"`
	ProjectID pgtype.UUID `json:"project_id"`
	Type      *string     `json:"type"`
	Lim       *int32      `json:"lim"`
}

type SearchItemsFuzzyRow struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee"`
	Position           float64         `json:"position"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	Tags               []string        `json:"tags"`
	Metadata           json.RawMessage `json:"metadata"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           *time.Time      `json:"closed_at"`
	DeletedAt          *time.Time      `json:"deleted_at"`
	Search             interface{}     `json:"search"`
	IdempotencyKey     *string         `json:"idempotency_key"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria"`
	Seq                int64           `json:"seq"`
	Ref                string          `json:"ref"`
	Version            int32           `json:"version"`
	Embedding          pgvec.Vector    `json:"embedding"`
	EmbeddingModel     string          `json:"embedding_model"`
	Sim                interface{}     `json:"sim"`
}

// Trigram (pg_trgm) fuzzy match for typos / partial refs / code fragments that
// English FTS misses. Ranked by similarity to title or ref.
func (q *Queries) SearchItemsFuzzy(ctx context.Context, arg SearchItemsFuzzyParams) ([]SearchItemsFuzzyRow, error) {
	rows, err := q.db.Query(ctx, searchItemsFuzzy,
		arg.Q,
		arg.ProjectID,
		arg.Type,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchItemsFuzzyRow
	for rows.Next() {
		var i SearchItemsFuzzyRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
