// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	pgvec "flightdeck/internal/pgvec"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createItemLink = `-- name: CreateItemLink :one
INSERT INTO item_links (from_item_id, to_item_id, kind)
VALUES ($1, $2, COALESCE($3::text, 'relates_to'))
ON CONFLICT (from_item_id, to_item_id, kind) DO UPDATE SET kind = EXCLUDED.kind
RETURNING id, from_item_id, to_item_id, kind, created_at
`

type CreateItemLinkParams struct {
	FromItemID uuid.UUID `json:"from_item_id"`
	ToItemID   uuid.UUID `json:"to_item_id"`
	Kind       *string   `json:"kind"`
}

func (q *Queries) CreateItemLink(ctx context.Context, arg CreateItemLinkParams) (ItemLink, error) {
	row := q.db.QueryRow(ctx, createItemLink, arg.FromItemID, arg.ToItemID, arg.Kind)
	var i ItemLink
	err := row.Scan(
		&i.ID,
		&i.FromItemID,
		&i.ToItemID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItemLink = `-- name: DeleteItemLink :exec
DELETE FROM item_links WHERE id = $1
`

func (q *Queries) DeleteItemLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemLink, id)
	return err
}

const listBlockingEdgesByProject = `-- name: ListBlockingEdgesByProject :many
SELECT l.to_item_id AS blocked_id,
       l.from_item_id AS blocker_id,
       b.title AS blocker_title,
       b.status AS blocker_status
FROM item_links l
JOIN items blocked ON blocked.id = l.to_item_id
    AND blocked.project_id = $1 AND blocked.deleted_at IS NULL
JOIN items b ON b.id = l.from_item_id AND b.deleted_at IS NULL
WHERE l.kind = 'blocks' AND b.status NOT IN ('done', 'wontfix')
`

type ListBlockingEdgesByProjectRow struct {
	BlockedID     uuid.UUID `json:"blocked_id"`
	BlockerID     uuid.UUID `json:"blocker_id"`
	BlockerTitle  string    `json:"blocker_title"`
	BlockerStatus string    `json:"blocker_status"`
}

// For a project, the active "blocks" edges: each row means blocked_id is blocked
// by blocker_id (whose status is still open). Used to flag non-ready open items.
func (q *Queries) ListBlockingEdgesByProject(ctx context.Context, projectID uuid.UUID) ([]ListBlockingEdgesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listBlockingEdgesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockingEdgesByProjectRow
	for rows.Next() {
		var i ListBlockingEdgesByProjectRow
		if err := rows.Scan(
			&i.BlockedID,
			&i.BlockerID,
			&i.BlockerTitle,
			&i.BlockerStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksForItem = `-- name: ListLinksForItem :many
SELECT id, from_item_id, to_item_id, kind, created_at FROM item_links
WHERE from_item_id = $1 OR to_item_id = $1
ORDER BY created_at
`

func (q *Queries) ListLinksForItem(ctx context.Context, fromItemID uuid.UUID) ([]ItemLink, error) {
	rows, err := q.db.Query(ctx, listLinksForItem, fromItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemLink
	for rows.Next() {
		var i ItemLink
		if err := rows.Scan(
			&i.ID,
			&i.FromItemID,
			&i.ToItemID,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenBlockingEdges = `-- name: ListOpenBlockingEdges :many
SELECT l.to_item_id AS blocked_id,
       l.from_item_id AS blocker_id,
       b.title AS blocker_title
FROM item_links l
JOIN items blocked ON blocked.id = l.to_item_id AND blocked.deleted_at IS NULL
JOIN items b ON b.id = l.from_item_id AND b.deleted_at IS NULL
WHERE l.kind = 'blocks' AND b.status NOT IN ('done', 'wontfix')
`

type ListOpenBlockingEdgesRow struct {
	BlockedID    uuid.UUID `json:"blocked_id"`
	BlockerID    uuid.UUID `json:"blocker_id"`
	BlockerTitle string    `json:"blocker_title"`
}

// Every active "blocks" edge across all projects: blocked_id is blocked by an
// open blocker. Used to annotate /items list responses with blocked flags.
func (q *Queries) ListOpenBlockingEdges(ctx context.Context) ([]ListOpenBlockingEdgesRow, error) {
	rows, err := q.db.Query(ctx, listOpenBlockingEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenBlockingEdgesRow
	for rows.Next() {
		var i ListOpenBlockingEdgesRow
		if err := rows.Scan(&i.BlockedID, &i.BlockerID, &i.BlockerTitle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyItems = `-- name: ListReadyItems :many
SELECT i.id, i.project_id, i.type, i.title, i.body, i.status, i.priority, i.assignee, i.position, i.source, i.external_ref, i.tags, i.metadata, i.created_at, i.updated_at, i.closed_at, i.deleted_at, i.search, i.idempotency_key, i.acceptance_criteria, i.seq, i.ref, i.version, i.embedding, i.embedding_model, p.slug AS project_slug
FROM items i
JOIN projects p ON p.id = i.project_id AND p.status = 'active'
WHERE i.deleted_at IS NULL
  AND i.status NOT IN ('done', 'wontfix')
  AND ($1::uuid IS NULL OR i.project_id = $1)
  AND NOT EXISTS (
      SELECT 1 FROM item_links l
      JOIN items b ON b.id = l.from_item_id AND b.deleted_at IS NULL
      WHERE l.kind = 'blocks' AND l.to_item_id = i.id
        AND b.status NOT IN ('done', 'wontfix')
  )
ORDER BY
    CASE i.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 WHEN 'med' THEN 2 ELSE 3 END,
    CASE i.status WHEN 'in_progress' THEN 0 WHEN 'todo' THEN 1 WHEN 'backlog' THEN 2 ELSE 3 END,
    i.updated_at ASC
LIMIT COALESCE($2::int, 20)
`

type ListReadyItemsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Lim       *int32      `json:"lim"`
}

type ListReadyItemsRow struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee"`
	Position           float64         `json:"position"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	Tags               []string        `json:"tags"`
	Metadata           json.RawMessage `json:"metadata"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           *time.Time      `json:"closed_at"`
	DeletedAt          *time.Time      `json:"deleted_at"`
	Search             interface{}     `json:"search"`
	IdempotencyKey     *string         `json:"idempotency_key"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria"`
	Seq                int64           `json:"seq"`
	Ref                string          `json:"ref"`
	Version            int32           `json:"version"`
	Embedding          pgvec.Vector    `json:"embedding"`
	EmbeddingModel     string          `json:"embedding_model"`
	ProjectSlug        string          `json:"project_slug"`
}

// Open items across active projects that are NOT blocked by any open blocker,
// ranked for "what should I work on": priority, then in_progress/todo, then age.
func (q *Queries) ListReadyItems(ctx context.Context, arg ListReadyItemsParams) ([]ListReadyItemsRow, error) {
	rows, err := q.db.Query(ctx, listReadyItems, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadyItemsRow
	for rows.Next() {
		var i ListReadyItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
