// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package store

import (
	"context"
	"time"
)

const listPurgeableAttachmentKeys = `-- name: ListPurgeableAttachmentKeys :many
SELECT a.object_key FROM attachments a
JOIN items i ON i.id = a.item_id
WHERE i.deleted_at IS NOT NULL AND i.deleted_at < $1
`

// Object keys owned by items about to be hard-deleted, so the maintenance
// sweep can remove the blobs before the rows cascade away.
func (q *Queries) ListPurgeableAttachmentKeys(ctx context.Context, deletedAt *time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, listPurgeableAttachmentKeys, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldActivity = `-- name: PurgeOldActivity :execrows
DELETE FROM activity
WHERE kind IN ('comment', 'created') AND created_at < $1
`

// Trim low-signal activity (comments and auto 'created' rows) older than the
// cutoff. Decisions, progress, status changes, and rejections are kept — they
// are the durable "why" an agent reads.
func (q *Queries) PurgeOldActivity(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldActivity, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeSoftDeletedItems = `-- name: PurgeSoftDeletedItems :execrows
DELETE FROM items WHERE deleted_at IS NOT NULL AND deleted_at < $1
`

// Hard-delete items soft-deleted before the cutoff, reclaiming index space and
// dropping FTS tombstones.
func (q *Queries) PurgeSoftDeletedItems(ctx context.Context, deletedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSoftDeletedItems, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
