// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package store

import (
	"context"
	"time"
)

const purgeOldActivity = `-- name: PurgeOldActivity :execrows
DELETE FROM activity
WHERE kind IN ('comment', 'created') AND created_at < $1
`

// Trim low-signal activity (comments and auto 'created' rows) older than the
// cutoff. Decisions, progress, status changes, and rejections are kept — they
// are the durable "why" an agent reads.
func (q *Queries) PurgeOldActivity(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldActivity, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeSoftDeletedItems = `-- name: PurgeSoftDeletedItems :execrows
DELETE FROM items WHERE deleted_at IS NOT NULL AND deleted_at < $1
`

// Hard-delete items soft-deleted before the cutoff, reclaiming index space and
// dropping FTS tombstones.
func (q *Queries) PurgeSoftDeletedItems(ctx context.Context, deletedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSoftDeletedItems, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
