// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"time"

	pgvec "flightdeck/internal/pgvec"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID         uuid.UUID       `json:"id"`
	ProjectID  uuid.UUID       `json:"project_id"`
	ItemID     pgtype.UUID     `json:"item_id"`
	Kind       string          `json:"kind"`
	Actor      string          `json:"actor"`
	Body       string          `json:"body"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  time.Time       `json:"created_at"`
	Search     interface{}     `json:"search"`
	Confidence string          `json:"confidence"`
}

type ActivityEmbedding struct {
	ActivityID uuid.UUID    `json:"activity_id"`
	Embedding  pgvec.Vector `json:"embedding"`
	Model      string       `json:"model"`
	CreatedAt  time.Time    `json:"created_at"`
}

type ApiKey struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	KeyHash    string     `json:"key_hash"`
	Scopes     []string   `json:"scopes"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	Revoked    bool       `json:"revoked"`
	ExpiresAt  *time.Time `json:"expires_at"`
}

type Item struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee"`
	Position           float64         `json:"position"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	Tags               []string        `json:"tags"`
	Metadata           json.RawMessage `json:"metadata"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           *time.Time      `json:"closed_at"`
	DeletedAt          *time.Time      `json:"deleted_at"`
	Search             interface{}     `json:"search"`
	IdempotencyKey     *string         `json:"idempotency_key"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria"`
	Seq                int64           `json:"seq"`
	Ref                string          `json:"ref"`
	Version            int32           `json:"version"`
	Embedding          pgvec.Vector    `json:"embedding"`
	EmbeddingModel     string          `json:"embedding_model"`
}

type ItemLink struct {
	ID         uuid.UUID `json:"id"`
	FromItemID uuid.UUID `json:"from_item_id"`
	ToItemID   uuid.UUID `json:"to_item_id"`
	Kind       string    `json:"kind"`
	CreatedAt  time.Time `json:"created_at"`
}

type ItemRef struct {
	ID        uuid.UUID `json:"id"`
	ItemID    uuid.UUID `json:"item_id"`
	Kind      string    `json:"kind"`
	Ref       string    `json:"ref"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type Project struct {
	ID           uuid.UUID `json:"id"`
	Slug         string    `json:"slug"`
	Name         string    `json:"name"`
	Status       string    `json:"status"`
	Summary      string    `json:"summary"`
	RepoUrl      *string   `json:"repo_url"`
	SiteUrl      *string   `json:"site_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Instructions string    `json:"instructions"`
	ItemSeq      int64     `json:"item_seq"`
	Aliases      []string  `json:"aliases"`
}

type Webhook struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Url       string      `json:"url"`
	Secret    string      `json:"secret"`
	Events    []string    `json:"events"`
	Active    bool        `json:"active"`
	CreatedAt time.Time   `json:"created_at"`
}

type WebhookEvent struct {
	ID               uuid.UUID       `json:"id"`
	ProjectID        pgtype.UUID     `json:"project_id"`
	Event            string          `json:"event"`
	Payload          json.RawMessage `json:"payload"`
	Attempts         int32           `json:"attempts"`
	NextAttemptAt    time.Time       `json:"next_attempt_at"`
	DeliveredAt      *time.Time      `json:"delivered_at"`
	LastError        string          `json:"last_error"`
	CreatedAt        time.Time       `json:"created_at"`
	DeliveredHookIds []uuid.UUID     `json:"delivered_hook_ids"`
	ParkedAt         *time.Time      `json:"parked_at"`
}
