// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeOAuthCode = `-- name: ConsumeOAuthCode :one
UPDATE oauth_codes SET used = true
WHERE code_hash = $1 AND used = false AND expires_at > now()
RETURNING code_hash, client_id, api_key_id, redirect_uri, code_challenge, scope, expires_at, used, created_at
`

// Single use: the UPDATE only matches an unused, unexpired code, so a replay
// gets no row.
func (q *Queries) ConsumeOAuthCode(ctx context.Context, codeHash string) (OauthCode, error) {
	row := q.db.QueryRow(ctx, consumeOAuthCode, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.ApiKeyID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.Scope,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const consumeOAuthRefresh = `-- name: ConsumeOAuthRefresh :one
UPDATE oauth_tokens SET revoked = true
WHERE refresh_hash = $1 AND revoked = false AND refresh_expires_at > now()
RETURNING id, client_id, api_key_id, access_hash, refresh_hash, scope, access_expires_at, refresh_expires_at, revoked, created_at, last_used_at
`

// Rotation: revoke the row holding this refresh token and hand back what is
// needed to mint its successor. A replayed refresh token matches nothing.
func (q *Queries) ConsumeOAuthRefresh(ctx context.Context, refreshHash string) (OauthToken, error) {
	row := q.db.QueryRow(ctx, consumeOAuthRefresh, refreshHash)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ApiKeyID,
		&i.AccessHash,
		&i.RefreshHash,
		&i.Scope,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (id, secret_hash, name, redirect_uris, auth_method)
VALUES ($1, $5, $2, $3, $4)
RETURNING id, secret_hash, name, redirect_uris, auth_method, created_at
`

type CreateOAuthClientParams struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	RedirectUris []string `json:"redirect_uris"`
	AuthMethod   string   `json:"auth_method"`
	SecretHash   *string  `json:"secret_hash"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.ID,
		arg.Name,
		arg.RedirectUris,
		arg.AuthMethod,
		arg.SecretHash,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.AuthMethod,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :exec
INSERT INTO oauth_codes (code_hash, client_id, api_key_id, redirect_uri, code_challenge, scope, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOAuthCodeParams struct {
	CodeHash      string    `json:"code_hash"`
	ClientID      string    `json:"client_id"`
	ApiKeyID      uuid.UUID `json:"api_key_id"`
	RedirectUri   string    `json:"redirect_uri"`
	CodeChallenge string    `json:"code_challenge"`
	Scope         string    `json:"scope"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createOAuthCode,
		arg.CodeHash,
		arg.ClientID,
		arg.ApiKeyID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.Scope,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthToken = `-- name: CreateOAuthToken :one
INSERT INTO oauth_tokens (client_id, api_key_id, access_hash, refresh_hash, scope, access_expires_at, refresh_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, client_id, api_key_id, access_hash, refresh_hash, scope, access_expires_at, refresh_expires_at, revoked, created_at, last_used_at
`

type CreateOAuthTokenParams struct {
	ClientID         string    `json:"client_id"`
	ApiKeyID         uuid.UUID `json:"api_key_id"`
	AccessHash       string    `json:"access_hash"`
	RefreshHash      string    `json:"refresh_hash"`
	Scope            string    `json:"scope"`
	AccessExpiresAt  time.Time `json:"access_expires_at"`
	RefreshExpiresAt time.Time `json:"refresh_expires_at"`
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, createOAuthToken,
		arg.ClientID,
		arg.ApiKeyID,
		arg.AccessHash,
		arg.RefreshHash,
		arg.Scope,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ApiKeyID,
		&i.AccessHash,
		&i.RefreshHash,
		&i.Scope,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, secret_hash, name, redirect_uris, auth_method, created_at FROM oauth_clients WHERE id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.AuthMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthTokenByAccessHash = `-- name: GetOAuthTokenByAccessHash :one
SELECT t.id, t.api_key_id, t.scope, t.last_used_at, k.name AS key_name, k.scopes AS key_scopes
FROM oauth_tokens t
JOIN api_keys k ON k.id = t.api_key_id
WHERE t.access_hash = $1 AND t.revoked = false AND t.access_expires_at > now()
  AND k.revoked = false AND (k.expires_at IS NULL OR k.expires_at > now())
`

type GetOAuthTokenByAccessHashRow struct {
	ID         uuid.UUID  `json:"id"`
	ApiKeyID   uuid.UUID  `json:"api_key_id"`
	Scope      string     `json:"scope"`
	LastUsedAt *time.Time `json:"last_used_at"`
	KeyName    string     `json:"key_name"`
	KeyScopes  []string   `json:"key_scopes"`
}

// Joins the backing key so a revoked or expired key invalidates its tokens.
func (q *Queries) GetOAuthTokenByAccessHash(ctx context.Context, accessHash string) (GetOAuthTokenByAccessHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenByAccessHash, accessHash)
	var i GetOAuthTokenByAccessHashRow
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.Scope,
		&i.LastUsedAt,
		&i.KeyName,
		&i.KeyScopes,
	)
	return i, err
}

const purgeExpiredOAuth = `-- name: PurgeExpiredOAuth :execrows
WITH c AS (DELETE FROM oauth_codes WHERE expires_at < now())
DELETE FROM oauth_tokens WHERE refresh_expires_at < now() OR (revoked AND created_at < now() - interval '1 day')
`

// Maintenance: codes and tokens past every usable window.
func (q *Queries) PurgeExpiredOAuth(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredOAuth)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchOAuthToken = `-- name: TouchOAuthToken :exec
UPDATE oauth_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchOAuthToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchOAuthToken, id)
	return err
}
