// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countItemsByStatus = `-- name: CountItemsByStatus :many
SELECT project_id, status, count(*) AS n
FROM items
WHERE deleted_at IS NULL
GROUP BY project_id, status
`

type CountItemsByStatusRow struct {
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
	N         int64     `json:"n"`
}

func (q *Queries) CountItemsByStatus(ctx context.Context) ([]CountItemsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countItemsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountItemsByStatusRow
	for rows.Next() {
		var i CountItemsByStatusRow
		if err := rows.Scan(&i.ProjectID, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countItemsByStatusForProject = `-- name: CountItemsByStatusForProject :many
SELECT status, count(*) AS n
FROM items
WHERE project_id = $1 AND deleted_at IS NULL
GROUP BY status
`

type CountItemsByStatusForProjectRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

// Single-project status counts — avoids the all-projects full scan when serving
// a single-project orient.
func (q *Queries) CountItemsByStatusForProject(ctx context.Context, projectID uuid.UUID) ([]CountItemsByStatusForProjectRow, error) {
	rows, err := q.db.Query(ctx, countItemsByStatusForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountItemsByStatusForProjectRow
	for rows.Next() {
		var i CountItemsByStatusForProjectRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (slug, name, status, summary, instructions, repo_url, site_url, aliases, parent_slug)
VALUES (
    $1,
    $2,
    COALESCE($3::text, 'active'),
    COALESCE($4::text, ''),
    COALESCE($5::text, ''),
    $6,
    $7,
    COALESCE($8::text[], '{}'),
    $9
)
RETURNING id, slug, name, status, summary, repo_url, site_url, created_at, updated_at, instructions, item_seq, aliases, parent_slug
`

type CreateProjectParams struct {
	Slug         string   `json:"slug"`
	Name         string   `json:"name"`
	Status       *string  `json:"status"`
	Summary      *string  `json:"summary"`
	Instructions *string  `json:"instructions"`
	RepoUrl      *string  `json:"repo_url"`
	SiteUrl      *string  `json:"site_url"`
	Aliases      []string `json:"aliases"`
	ParentSlug   *string  `json:"parent_slug"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Slug,
		arg.Name,
		arg.Status,
		arg.Summary,
		arg.Instructions,
		arg.RepoUrl,
		arg.SiteUrl,
		arg.Aliases,
		arg.ParentSlug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Summary,
		&i.RepoUrl,
		&i.SiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Instructions,
		&i.ItemSeq,
		&i.Aliases,
		&i.ParentSlug,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, slug, name, status, summary, repo_url, site_url, created_at, updated_at, instructions, item_seq, aliases, parent_slug FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Summary,
		&i.RepoUrl,
		&i.SiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Instructions,
		&i.ItemSeq,
		&i.Aliases,
		&i.ParentSlug,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, status, summary, repo_url, site_url, created_at, updated_at, instructions, item_seq, aliases, parent_slug FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Summary,
		&i.RepoUrl,
		&i.SiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Instructions,
		&i.ItemSeq,
		&i.Aliases,
		&i.ParentSlug,
	)
	return i, err
}

const listChildProjects = `-- name: ListChildProjects :many
SELECT slug, name, status, summary FROM projects
WHERE parent_slug = $1
ORDER BY name
`

type ListChildProjectsRow struct {
	Slug    string `json:"slug"`
	Name    string `json:"name"`
	Status  string `json:"status"`
	Summary string `json:"summary"`
}

func (q *Queries) ListChildProjects(ctx context.Context, parentSlug *string) ([]ListChildProjectsRow, error) {
	rows, err := q.db.Query(ctx, listChildProjects, parentSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildProjectsRow
	for rows.Next() {
		var i ListChildProjectsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, status, summary, repo_url, site_url, created_at, updated_at, instructions, item_seq, aliases, parent_slug FROM projects
WHERE ($1::text IS NULL OR status = $1)
ORDER BY
    CASE status WHEN 'active' THEN 0 WHEN 'paused' THEN 1 WHEN 'done' THEN 2 ELSE 3 END,
    updated_at DESC
`

func (q *Queries) ListProjects(ctx context.Context, status *string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Summary,
			&i.RepoUrl,
			&i.SiteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Instructions,
			&i.ItemSeq,
			&i.Aliases,
			&i.ParentSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectDescendants = `-- name: ProjectDescendants :many
WITH RECURSIVE subtree (slug) AS (
    SELECT root.slug FROM projects root WHERE root.slug = $1
    UNION
    SELECT p.slug FROM projects p JOIN subtree s ON p.parent_slug = s.slug
)
SELECT s.slug FROM subtree s
`

// Slugs of the subtree rooted at $1, root included. UNION (not UNION ALL)
// deduplicates, so this terminates even if a concurrent parent change ever
// raced a cycle past validation.
func (q *Queries) ProjectDescendants(ctx context.Context, slug string) ([]string, error) {
	rows, err := q.db.Query(ctx, projectDescendants, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectInstructions = `-- name: SetProjectInstructions :one
UPDATE projects SET instructions = $2, updated_at = now()
WHERE slug = $1
RETURNING id, slug, name, status, summary, repo_url, site_url, created_at, updated_at, instructions, item_seq, aliases, parent_slug
`

type SetProjectInstructionsParams struct {
	Slug         string `json:"slug"`
	Instructions string `json:"instructions"`
}

func (q *Queries) SetProjectInstructions(ctx context.Context, arg SetProjectInstructionsParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectInstructions, arg.Slug, arg.Instructions)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Summary,
		&i.RepoUrl,
		&i.SiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Instructions,
		&i.ItemSeq,
		&i.Aliases,
		&i.ParentSlug,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name         = COALESCE($1::text, name),
    status       = COALESCE($2::text, status),
    summary      = COALESCE($3::text, summary),
    instructions = COALESCE($4::text, instructions),
    repo_url     = COALESCE($5::text, repo_url),
    site_url     = COALESCE($6::text, site_url),
    aliases      = COALESCE($7::text[], aliases),
    parent_slug  = CASE WHEN $8::bool
                        THEN $9::text
                        ELSE parent_slug END,
    updated_at   = now()
WHERE slug = $10
RETURNING id, slug, name, status, summary, repo_url, site_url, created_at, updated_at, instructions, item_seq, aliases, parent_slug
`

type UpdateProjectParams struct {
	Name         *string  `json:"name"`
	Status       *string  `json:"status"`
	Summary      *string  `json:"summary"`
	Instructions *string  `json:"instructions"`
	RepoUrl      *string  `json:"repo_url"`
	SiteUrl      *string  `json:"site_url"`
	Aliases      []string `json:"aliases"`
	SetParent    bool     `json:"set_parent"`
	ParentSlug   *string  `json:"parent_slug"`
	Slug         string   `json:"slug"`
}

// parent_slug needs a tri-state (leave / set / clear) that COALESCE can't
// express, so set_parent gates the change and parent_slug carries set-vs-clear.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Status,
		arg.Summary,
		arg.Instructions,
		arg.RepoUrl,
		arg.SiteUrl,
		arg.Aliases,
		arg.SetParent,
		arg.ParentSlug,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Summary,
		&i.RepoUrl,
		&i.SiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Instructions,
		&i.ItemSeq,
		&i.Aliases,
		&i.ParentSlug,
	)
	return i, err
}

const updateProjectSummary = `-- name: UpdateProjectSummary :one
UPDATE projects SET summary = $2, updated_at = now()
WHERE slug = $1
RETURNING id, slug, name, status, summary, repo_url, site_url, created_at, updated_at, instructions, item_seq, aliases, parent_slug
`

type UpdateProjectSummaryParams struct {
	Slug    string `json:"slug"`
	Summary string `json:"summary"`
}

func (q *Queries) UpdateProjectSummary(ctx context.Context, arg UpdateProjectSummaryParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectSummary, arg.Slug, arg.Summary)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Summary,
		&i.RepoUrl,
		&i.SiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Instructions,
		&i.ItemSeq,
		&i.Aliases,
		&i.ParentSlug,
	)
	return i, err
}
