// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	ActivityKindCountsSince(ctx context.Context, arg ActivityKindCountsSinceParams) ([]ActivityKindCountsSinceRow, error)
	CountActivitySince(ctx context.Context, arg CountActivitySinceParams) (int64, error)
	CountDistinctItemsTouchedSince(ctx context.Context, arg CountDistinctItemsTouchedSinceParams) (int64, error)
	CountItemsByStatus(ctx context.Context) ([]CountItemsByStatusRow, error)
	// Single-project status counts — avoids the all-projects full scan when serving
	// a single-project orient.
	CountItemsByStatusForProject(ctx context.Context, projectID uuid.UUID) ([]CountItemsByStatusForProjectRow, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateItemLink(ctx context.Context, arg CreateItemLinkParams) (ItemLink, error)
	CreateItemRef(ctx context.Context, arg CreateItemRefParams) (ItemRef, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	DailyToolCalls(ctx context.Context, calledAt time.Time) ([]DailyToolCallsRow, error)
	DeleteItemLink(ctx context.Context, id uuid.UUID) error
	DeleteItemRef(ctx context.Context, id uuid.UUID) error
	DeleteWebhook(ctx context.Context, id uuid.UUID) error
	// --- durable outbox ---
	// Called inside the originating write's transaction (transactional outbox).
	EnqueueWebhookEvent(ctx context.Context, arg EnqueueWebhookEventParams) (WebhookEvent, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetItem(ctx context.Context, id uuid.UUID) (Item, error)
	// Scoped to the project: idempotency keys are only unique per project, so a
	// cross-project key reuse must not return another project's item.
	GetItemByIdempotencyKey(ctx context.Context, arg GetItemByIdempotencyKeyParams) (Item, error)
	GetItemByRef(ctx context.Context, lower string) (Item, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	// Upsert so marking a row 'failed' and later embedding it (or vice versa in a
	// race) never errors.
	InsertActivityEmbedding(ctx context.Context, arg InsertActivityEmbeddingParams) error
	InsertSearchLog(ctx context.Context, arg InsertSearchLogParams) error
	InsertToolCall(ctx context.Context, arg InsertToolCallParams) error
	// Atomically claim a batch of due events and push their next attempt into the
	// future (a lease), so delivery happens outside the row lock and concurrent
	// workers never grab the same event.
	LeaseWebhookEvents(ctx context.Context, lim int32) ([]WebhookEvent, error)
	ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error)
	// Webhooks subscribed to this project (or all projects) and this event (or all).
	ListActiveWebhooksForEvent(ctx context.Context, arg ListActiveWebhooksForEventParams) ([]Webhook, error)
	ListActivity(ctx context.Context, arg ListActivityParams) ([]Activity, error)
	// High-signal activity (decisions, progress, rejections — the "why" agents
	// search for) that has no embedding yet. Rows with a 'failed' marker are poison
	// and skipped. Activity is immutable, so there is no re-embed-on-edit path.
	ListActivityNeedingEmbedding(ctx context.Context, lim int32) ([]ListActivityNeedingEmbeddingRow, error)
	// For a project, the active "blocks" edges: each row means blocked_id is blocked
	// by blocker_id (whose status is still open). Used to flag non-ready open items.
	ListBlockingEdgesByProject(ctx context.Context, projectID uuid.UUID) ([]ListBlockingEdgesByProjectRow, error)
	// Dead-lettered / erroring events for operator visibility (last_error set).
	ListFailedWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error)
	ListItemRefs(ctx context.Context, itemID uuid.UUID) ([]ItemRef, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	// Live items whose embedding is missing (never embedded, or invalidated by a
	// content edit). The background embedder drains this in batches. Rows marked
	// embedding_model='failed' are poison (repeatedly rejected) and skipped so one
	// bad item can't stall the whole backlog; a content edit clears the marker.
	ListItemsNeedingEmbedding(ctx context.Context, lim int32) ([]ListItemsNeedingEmbeddingRow, error)
	ListLinksForItem(ctx context.Context, fromItemID uuid.UUID) ([]ItemLink, error)
	// Every active "blocks" edge across all projects: blocked_id is blocked by an
	// open blocker. Used to annotate /items list responses with blocked flags.
	ListOpenBlockingEdges(ctx context.Context) ([]ListOpenBlockingEdgesRow, error)
	ListOpenItemsByProject(ctx context.Context, arg ListOpenItemsByProjectParams) ([]Item, error)
	ListProjects(ctx context.Context, status *string) ([]Project, error)
	// Open items across active projects that are NOT blocked by any open blocker,
	// ranked for "what should I work on": priority, then in_progress/todo, then age.
	ListReadyItems(ctx context.Context, arg ListReadyItemsParams) ([]ListReadyItemsRow, error)
	ListRecentActivityByProject(ctx context.Context, arg ListRecentActivityByProjectParams) ([]Activity, error)
	ListRecentDecisionsByProject(ctx context.Context, arg ListRecentDecisionsByProjectParams) ([]Activity, error)
	ListRejectedByProject(ctx context.Context, arg ListRejectedByProjectParams) ([]Activity, error)
	// in_progress items whose last update is older than the cutoff.
	ListStaleInProgress(ctx context.Context, updatedAt time.Time) ([]ListStaleInProgressRow, error)
	// active projects whose latest activity is newer than the last summary refresh.
	ListStaleProjectSummaries(ctx context.Context) ([]ListStaleProjectSummariesRow, error)
	// Top-N open items for every active project in a single windowed query — replaces
	// the per-project N+1 loop that built the global "load the map" view.
	ListTopOpenItemsPerProject(ctx context.Context, perProject int32) ([]ListTopOpenItemsPerProjectRow, error)
	// bugs still sitting in backlog (never triaged) older than the cutoff.
	ListUntriagedBugs(ctx context.Context, createdAt time.Time) ([]ListUntriagedBugsRow, error)
	ListWebhooks(ctx context.Context) ([]Webhook, error)
	// Park a poison item so the embedder stops retrying it. Guarded by the
	// still-NULL check so a successful concurrent embed isn't clobbered.
	MarkItemEmbeddingFailed(ctx context.Context, id uuid.UUID) error
	MarkWebhookEventDelivered(ctx context.Context, arg MarkWebhookEventDeliveredParams) error
	// Dead-letter: attempts exhausted. Distinct from delivered_at so the two states
	// can't be conflated; the row stays visible for the operator dead-letter view.
	ParkWebhookEvent(ctx context.Context, arg ParkWebhookEventParams) error
	PurgeDeliveredWebhookEvents(ctx context.Context, deliveredAt *time.Time) (int64, error)
	// Trim low-signal activity (comments and auto 'created' rows) older than the
	// cutoff. Decisions, progress, status changes, and rejections are kept — they
	// are the durable "why" an agent reads.
	PurgeOldActivity(ctx context.Context, createdAt time.Time) (int64, error)
	PurgeOldSearchLog(ctx context.Context, searchedAt time.Time) (int64, error)
	PurgeOldToolCalls(ctx context.Context, calledAt time.Time) (int64, error)
	PurgeParkedWebhookEvents(ctx context.Context, parkedAt *time.Time) (int64, error)
	// Hard-delete items soft-deleted before the cutoff, reclaiming index space and
	// dropping FTS tombstones.
	PurgeSoftDeletedItems(ctx context.Context, deletedAt *time.Time) (int64, error)
	RecentToolErrors(ctx context.Context, calledAt time.Time) ([]RecentToolErrorsRow, error)
	RecentZeroResultSearches(ctx context.Context, searchedAt time.Time) ([]RecentZeroResultSearchesRow, error)
	// delivered_hook_ids records the subscribers that already ACKed this event, so
	// the retry only re-POSTs to the ones still failing (no duplicate deliveries).
	RescheduleWebhookEvent(ctx context.Context, arg RescheduleWebhookEventParams) error
	RevokeAPIKey(ctx context.Context, id uuid.UUID) (RevokeAPIKeyRow, error)
	// Replace a key's secret in place (same id/name/scopes), clearing revoked/expiry.
	RotateAPIKey(ctx context.Context, arg RotateAPIKeyParams) (RotateAPIKeyRow, error)
	SearchActivity(ctx context.Context, arg SearchActivityParams) ([]SearchActivityRow, error)
	// Approximate nearest-neighbour search over decision/progress bodies by cosine
	// distance, bounded by max_distance like the item variant.
	SearchActivitySemantic(ctx context.Context, arg SearchActivitySemanticParams) ([]SearchActivitySemanticRow, error)
	SearchItems(ctx context.Context, arg SearchItemsParams) ([]SearchItemsRow, error)
	// Trigram (pg_trgm) fuzzy match for typos / partial refs / code fragments that
	// English FTS misses. Ranked by similarity to title or ref.
	SearchItemsFuzzy(ctx context.Context, arg SearchItemsFuzzyParams) ([]SearchItemsFuzzyRow, error)
	// Approximate nearest-neighbour search by cosine distance. Only rows within
	// max_distance are returned, so an off-topic query yields nothing (and the
	// caller falls through to trigram) rather than surfacing the globally-closest
	// but irrelevant items.
	SearchItemsSemantic(ctx context.Context, arg SearchItemsSemanticParams) ([]SearchItemsSemanticRow, error)
	// semantic_rescues / trigram_rescues: searches where lexical FTS found nothing
	// but a fallback tier did — direct evidence those tiers earn their keep.
	SearchUsageSummary(ctx context.Context, searchedAt time.Time) (SearchUsageSummaryRow, error)
	// Store an embedding, but only if the item's content hasn't changed since it was
	// read for embedding (guarded by the still-NULL check) — so an edit that races
	// the embedder isn't clobbered with a stale vector.
	SetItemEmbedding(ctx context.Context, arg SetItemEmbeddingParams) error
	SetProjectInstructions(ctx context.Context, arg SetProjectInstructionsParams) (Project, error)
	SoftDeleteItem(ctx context.Context, id uuid.UUID) (Item, error)
	// Per-tool behavior over a window: volume, error count, latency percentiles,
	// and average result size (the token-cost proxy agents pay to call it).
	ToolCallStats(ctx context.Context, calledAt time.Time) ([]ToolCallStatsRow, error)
	TopProjectsByToolCalls(ctx context.Context, calledAt time.Time) ([]TopProjectsByToolCallsRow, error)
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	// Bumps version on every write. When expected_version is supplied it acts as a
	// compare-and-swap: a mismatch matches no row (caller maps that to a conflict).
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectSummary(ctx context.Context, arg UpdateProjectSummaryParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
