// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActivitySince = `-- name: CountActivitySince :one
SELECT count(*) FROM activity WHERE project_id = $1 AND created_at > $2
`

type CountActivitySinceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CountActivitySince(ctx context.Context, arg CountActivitySinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivitySince, arg.ProjectID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemRef = `-- name: CreateItemRef :one
INSERT INTO item_refs (item_id, kind, ref, label)
VALUES (
    $1,
    COALESCE($2::text, 'url'),
    $3,
    COALESCE($4::text, '')
)
RETURNING id, item_id, kind, ref, label, created_at
`

type CreateItemRefParams struct {
	ItemID uuid.UUID `json:"item_id"`
	Kind   *string   `json:"kind"`
	Ref    string    `json:"ref"`
	Label  *string   `json:"label"`
}

func (q *Queries) CreateItemRef(ctx context.Context, arg CreateItemRefParams) (ItemRef, error) {
	row := q.db.QueryRow(ctx, createItemRef,
		arg.ItemID,
		arg.Kind,
		arg.Ref,
		arg.Label,
	)
	var i ItemRef
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Kind,
		&i.Ref,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItemRef = `-- name: DeleteItemRef :exec
DELETE FROM item_refs WHERE id = $1
`

func (q *Queries) DeleteItemRef(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemRef, id)
	return err
}

const getItemByIdempotencyKey = `-- name: GetItemByIdempotencyKey :one
SELECT id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model FROM items
WHERE project_id = $1 AND idempotency_key = $2 AND deleted_at IS NULL
`

type GetItemByIdempotencyKeyParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

// Scoped to the project: idempotency keys are only unique per project, so a
// cross-project key reuse must not return another project's item.
func (q *Queries) GetItemByIdempotencyKey(ctx context.Context, arg GetItemByIdempotencyKeyParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.Source,
		&i.ExternalRef,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Search,
		&i.IdempotencyKey,
		&i.AcceptanceCriteria,
		&i.Seq,
		&i.Ref,
		&i.Version,
		&i.Embedding,
		&i.EmbeddingModel,
	)
	return i, err
}

const listItemRefs = `-- name: ListItemRefs :many
SELECT id, item_id, kind, ref, label, created_at FROM item_refs WHERE item_id = $1 ORDER BY created_at
`

func (q *Queries) ListItemRefs(ctx context.Context, itemID uuid.UUID) ([]ItemRef, error) {
	rows, err := q.db.Query(ctx, listItemRefs, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemRef
	for rows.Next() {
		var i ItemRef
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Kind,
			&i.Ref,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRejectedByProject = `-- name: ListRejectedByProject :many
SELECT id, project_id, item_id, kind, actor, body, metadata, created_at, search, confidence FROM activity
WHERE project_id = $1 AND kind = 'rejected'
ORDER BY created_at DESC
LIMIT $2
`

type ListRejectedByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListRejectedByProject(ctx context.Context, arg ListRejectedByProjectParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listRejectedByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ItemID,
			&i.Kind,
			&i.Actor,
			&i.Body,
			&i.Metadata,
			&i.CreatedAt,
			&i.Search,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
