// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sharing.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectShare = `-- name: CreateProjectShare :one
INSERT INTO project_shares (
    project_id, peer_name, mailbox_url,
    send_mailbox, send_token, recv_mailbox, recv_token,
    secret, client_cert, client_key, ca_pem
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, project_id, peer_name, mailbox_url, send_mailbox, send_token, recv_mailbox, recv_token, secret, client_cert, client_key, ca_pem, enabled, last_send_at, last_recv_at, last_error, created_at, updated_at
`

type CreateProjectShareParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	PeerName    string    `json:"peer_name"`
	MailboxUrl  string    `json:"mailbox_url"`
	SendMailbox string    `json:"send_mailbox"`
	SendToken   string    `json:"send_token"`
	RecvMailbox string    `json:"recv_mailbox"`
	RecvToken   string    `json:"recv_token"`
	Secret      []byte    `json:"secret"`
	ClientCert  string    `json:"client_cert"`
	ClientKey   string    `json:"client_key"`
	CaPem       string    `json:"ca_pem"`
}

func (q *Queries) CreateProjectShare(ctx context.Context, arg CreateProjectShareParams) (ProjectShare, error) {
	row := q.db.QueryRow(ctx, createProjectShare,
		arg.ProjectID,
		arg.PeerName,
		arg.MailboxUrl,
		arg.SendMailbox,
		arg.SendToken,
		arg.RecvMailbox,
		arg.RecvToken,
		arg.Secret,
		arg.ClientCert,
		arg.ClientKey,
		arg.CaPem,
	)
	var i ProjectShare
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PeerName,
		&i.MailboxUrl,
		&i.SendMailbox,
		&i.SendToken,
		&i.RecvMailbox,
		&i.RecvToken,
		&i.Secret,
		&i.ClientCert,
		&i.ClientKey,
		&i.CaPem,
		&i.Enabled,
		&i.LastSendAt,
		&i.LastRecvAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectShare = `-- name: DeleteProjectShare :exec
DELETE FROM project_shares WHERE id = $1
`

func (q *Queries) DeleteProjectShare(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectShare, id)
	return err
}

const getItemForSync = `-- name: GetItemForSync :one
SELECT id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model FROM items WHERE id = $1
`

func (q *Queries) GetItemForSync(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemForSync, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.Source,
		&i.ExternalRef,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Search,
		&i.IdempotencyKey,
		&i.AcceptanceCriteria,
		&i.Seq,
		&i.Ref,
		&i.Version,
		&i.Embedding,
		&i.EmbeddingModel,
	)
	return i, err
}

const getProjectShare = `-- name: GetProjectShare :one
SELECT id, project_id, peer_name, mailbox_url, send_mailbox, send_token, recv_mailbox, recv_token, secret, client_cert, client_key, ca_pem, enabled, last_send_at, last_recv_at, last_error, created_at, updated_at FROM project_shares WHERE id = $1
`

func (q *Queries) GetProjectShare(ctx context.Context, id uuid.UUID) (ProjectShare, error) {
	row := q.db.QueryRow(ctx, getProjectShare, id)
	var i ProjectShare
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PeerName,
		&i.MailboxUrl,
		&i.SendMailbox,
		&i.SendToken,
		&i.RecvMailbox,
		&i.RecvToken,
		&i.Secret,
		&i.ClientCert,
		&i.ClientKey,
		&i.CaPem,
		&i.Enabled,
		&i.LastSendAt,
		&i.LastRecvAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShareState = `-- name: GetShareState :one
SELECT share_id, entity_kind, entity_id, sent_hash, base_hash, synced_at FROM project_share_state
WHERE share_id = $1 AND entity_kind = $2 AND entity_id = $3
`

type GetShareStateParams struct {
	ShareID    uuid.UUID `json:"share_id"`
	EntityKind string    `json:"entity_kind"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetShareState(ctx context.Context, arg GetShareStateParams) (ProjectShareState, error) {
	row := q.db.QueryRow(ctx, getShareState, arg.ShareID, arg.EntityKind, arg.EntityID)
	var i ProjectShareState
	err := row.Scan(
		&i.ShareID,
		&i.EntityKind,
		&i.EntityID,
		&i.SentHash,
		&i.BaseHash,
		&i.SyncedAt,
	)
	return i, err
}

const listActivityForSync = `-- name: ListActivityForSync :many
SELECT id, project_id, item_id, kind, actor, body, metadata, created_at, search, confidence FROM activity WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListActivityForSync(ctx context.Context, projectID uuid.UUID) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivityForSync, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ItemID,
			&i.Kind,
			&i.Actor,
			&i.Body,
			&i.Metadata,
			&i.CreatedAt,
			&i.Search,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledProjectShares = `-- name: ListEnabledProjectShares :many
SELECT id, project_id, peer_name, mailbox_url, send_mailbox, send_token, recv_mailbox, recv_token, secret, client_cert, client_key, ca_pem, enabled, last_send_at, last_recv_at, last_error, created_at, updated_at FROM project_shares WHERE enabled ORDER BY created_at
`

// Drives the sync loop: every share it should be exchanging messages for.
func (q *Queries) ListEnabledProjectShares(ctx context.Context) ([]ProjectShare, error) {
	rows, err := q.db.Query(ctx, listEnabledProjectShares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectShare
	for rows.Next() {
		var i ProjectShare
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PeerName,
			&i.MailboxUrl,
			&i.SendMailbox,
			&i.SendToken,
			&i.RecvMailbox,
			&i.RecvToken,
			&i.Secret,
			&i.ClientCert,
			&i.ClientKey,
			&i.CaPem,
			&i.Enabled,
			&i.LastSendAt,
			&i.LastRecvAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsForSync = `-- name: ListItemsForSync :many
SELECT id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model FROM items WHERE project_id = $1
`

// Everything in the project, soft-deleted rows included: a deletion is a change
// the peer needs to hear about.
func (q *Queries) ListItemsForSync(ctx context.Context, projectID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsForSync, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.Source,
			&i.ExternalRef,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.DeletedAt,
			&i.Search,
			&i.IdempotencyKey,
			&i.AcceptanceCriteria,
			&i.Seq,
			&i.Ref,
			&i.Version,
			&i.Embedding,
			&i.EmbeddingModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectShares = `-- name: ListProjectShares :many
SELECT id, project_id, peer_name, mailbox_url, send_mailbox, send_token, recv_mailbox, recv_token, secret, client_cert, client_key, ca_pem, enabled, last_send_at, last_recv_at, last_error, created_at, updated_at FROM project_shares ORDER BY created_at
`

func (q *Queries) ListProjectShares(ctx context.Context) ([]ProjectShare, error) {
	rows, err := q.db.Query(ctx, listProjectShares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectShare
	for rows.Next() {
		var i ProjectShare
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PeerName,
			&i.MailboxUrl,
			&i.SendMailbox,
			&i.SendToken,
			&i.RecvMailbox,
			&i.RecvToken,
			&i.Secret,
			&i.ClientCert,
			&i.ClientKey,
			&i.CaPem,
			&i.Enabled,
			&i.LastSendAt,
			&i.LastRecvAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareStateHashes = `-- name: ListShareStateHashes :many
SELECT entity_kind, entity_id, sent_hash, base_hash FROM project_share_state
WHERE share_id = $1
`

type ListShareStateHashesRow struct {
	EntityKind string    `json:"entity_kind"`
	EntityID   uuid.UUID `json:"entity_id"`
	SentHash   string    `json:"sent_hash"`
	BaseHash   string    `json:"base_hash"`
}

func (q *Queries) ListShareStateHashes(ctx context.Context, shareID uuid.UUID) ([]ListShareStateHashesRow, error) {
	rows, err := q.db.Query(ctx, listShareStateHashes, shareID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShareStateHashesRow
	for rows.Next() {
		var i ListShareStateHashesRow
		if err := rows.Scan(
			&i.EntityKind,
			&i.EntityID,
			&i.SentHash,
			&i.BaseHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesForProject = `-- name: ListSharesForProject :many
SELECT id, project_id, peer_name, mailbox_url, send_mailbox, send_token, recv_mailbox, recv_token, secret, client_cert, client_key, ca_pem, enabled, last_send_at, last_recv_at, last_error, created_at, updated_at FROM project_shares WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListSharesForProject(ctx context.Context, projectID uuid.UUID) ([]ProjectShare, error) {
	rows, err := q.db.Query(ctx, listSharesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectShare
	for rows.Next() {
		var i ProjectShare
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PeerName,
			&i.MailboxUrl,
			&i.SendMailbox,
			&i.SendToken,
			&i.RecvMailbox,
			&i.RecvToken,
			&i.Secret,
			&i.ClientCert,
			&i.ClientKey,
			&i.CaPem,
			&i.Enabled,
			&i.LastSendAt,
			&i.LastRecvAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordApplied = `-- name: RecordApplied :exec
INSERT INTO project_share_state (share_id, entity_kind, entity_id, sent_hash, base_hash)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (share_id, entity_kind, entity_id)
DO UPDATE SET sent_hash = EXCLUDED.sent_hash, base_hash = EXCLUDED.base_hash, synced_at = now()
`

type RecordAppliedParams struct {
	ShareID    uuid.UUID `json:"share_id"`
	EntityKind string    `json:"entity_kind"`
	EntityID   uuid.UUID `json:"entity_id"`
	SentHash   string    `json:"sent_hash"`
}

// After applying a peer's change both sides hold this content, so it becomes
// the new agreed base AND the echo guard.
func (q *Queries) RecordApplied(ctx context.Context, arg RecordAppliedParams) error {
	_, err := q.db.Exec(ctx, recordApplied,
		arg.ShareID,
		arg.EntityKind,
		arg.EntityID,
		arg.SentHash,
	)
	return err
}

const recordMergedBase = `-- name: RecordMergedBase :exec
INSERT INTO project_share_state (share_id, entity_kind, entity_id, base_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (share_id, entity_kind, entity_id)
DO UPDATE SET base_hash = EXCLUDED.base_hash, synced_at = now()
`

type RecordMergedBaseParams struct {
	ShareID    uuid.UUID `json:"share_id"`
	EntityKind string    `json:"entity_kind"`
	EntityID   uuid.UUID `json:"entity_id"`
	BaseHash   string    `json:"base_hash"`
}

// A conflict merge produces content the peer has NOT seen. base_hash advances
// to the merged result, but sent_hash is left behind so the outbound pass
// notices the difference and pushes the merge back to the peer.
func (q *Queries) RecordMergedBase(ctx context.Context, arg RecordMergedBaseParams) error {
	_, err := q.db.Exec(ctx, recordMergedBase,
		arg.ShareID,
		arg.EntityKind,
		arg.EntityID,
		arg.BaseHash,
	)
	return err
}

const recordSent = `-- name: RecordSent :exec
INSERT INTO project_share_state (share_id, entity_kind, entity_id, sent_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (share_id, entity_kind, entity_id)
DO UPDATE SET sent_hash = EXCLUDED.sent_hash, synced_at = now()
`

type RecordSentParams struct {
	ShareID    uuid.UUID `json:"share_id"`
	EntityKind string    `json:"entity_kind"`
	EntityID   uuid.UUID `json:"entity_id"`
	SentHash   string    `json:"sent_hash"`
}

// Advances only the echo guard. base_hash is deliberately untouched: we have
// put this content on the wire, but the peer has not confirmed it, and it may
// be editing the same row right now.
func (q *Queries) RecordSent(ctx context.Context, arg RecordSentParams) error {
	_, err := q.db.Exec(ctx, recordSent,
		arg.ShareID,
		arg.EntityKind,
		arg.EntityID,
		arg.SentHash,
	)
	return err
}

const recordShareError = `-- name: RecordShareError :exec
UPDATE project_shares SET last_error = $2, updated_at = now() WHERE id = $1
`

type RecordShareErrorParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

// Surfaced in the UI so a share that silently stopped working is visible
// rather than just quietly stale.
func (q *Queries) RecordShareError(ctx context.Context, arg RecordShareErrorParams) error {
	_, err := q.db.Exec(ctx, recordShareError, arg.ID, arg.LastError)
	return err
}

const recordShareRecv = `-- name: RecordShareRecv :exec
UPDATE project_shares SET last_recv_at = now(), last_error = '', updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordShareRecv(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordShareRecv, id)
	return err
}

const recordShareSend = `-- name: RecordShareSend :exec
UPDATE project_shares SET last_send_at = now(), last_error = '', updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordShareSend(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordShareSend, id)
	return err
}

const setShareEnabled = `-- name: SetShareEnabled :exec
UPDATE project_shares SET enabled = $2, updated_at = now() WHERE id = $1
`

type SetShareEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetShareEnabled(ctx context.Context, arg SetShareEnabledParams) error {
	_, err := q.db.Exec(ctx, setShareEnabled, arg.ID, arg.Enabled)
	return err
}

const upsertSyncedActivity = `-- name: UpsertSyncedActivity :exec
INSERT INTO activity (id, project_id, item_id, kind, actor, body, confidence, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO NOTHING
`

type UpsertSyncedActivityParams struct {
	ID         uuid.UUID       `json:"id"`
	ProjectID  uuid.UUID       `json:"project_id"`
	ItemID     pgtype.UUID     `json:"item_id"`
	Kind       string          `json:"kind"`
	Actor      string          `json:"actor"`
	Body       string          `json:"body"`
	Confidence string          `json:"confidence"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  time.Time       `json:"created_at"`
}

// Activity is append-only, so a conflict means we have already seen this row
// and there is nothing to change.
func (q *Queries) UpsertSyncedActivity(ctx context.Context, arg UpsertSyncedActivityParams) error {
	_, err := q.db.Exec(ctx, upsertSyncedActivity,
		arg.ID,
		arg.ProjectID,
		arg.ItemID,
		arg.Kind,
		arg.Actor,
		arg.Body,
		arg.Confidence,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const upsertSyncedItem = `-- name: UpsertSyncedItem :one
INSERT INTO items (
    id, project_id, type, title, body, status, priority, assignee,
    source, external_ref, tags, metadata, acceptance_criteria,
    created_at, updated_at, closed_at, deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16, $17
)
ON CONFLICT (id) DO UPDATE SET
    type                = EXCLUDED.type,
    title               = EXCLUDED.title,
    body                = EXCLUDED.body,
    status              = EXCLUDED.status,
    priority            = EXCLUDED.priority,
    assignee            = EXCLUDED.assignee,
    external_ref        = EXCLUDED.external_ref,
    tags                = EXCLUDED.tags,
    metadata            = EXCLUDED.metadata,
    acceptance_criteria = EXCLUDED.acceptance_criteria,
    updated_at          = EXCLUDED.updated_at,
    closed_at           = EXCLUDED.closed_at,
    deleted_at          = EXCLUDED.deleted_at,
    -- Content changed under it, so the local embedding is stale; NULL makes the
    -- background embedder pick it up again.
    embedding           = NULL,
    embedding_model     = '',
    version             = items.version + 1
RETURNING id, project_id, type, title, body, status, priority, assignee, position, source, external_ref, tags, metadata, created_at, updated_at, closed_at, deleted_at, search, idempotency_key, acceptance_criteria, seq, ref, version, embedding, embedding_model
`

type UpsertSyncedItemParams struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	Tags               []string        `json:"tags"`
	Metadata           json.RawMessage `json:"metadata"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClosedAt           *time.Time      `json:"closed_at"`
	DeletedAt          *time.Time      `json:"deleted_at"`
}

// Applies a peer's item. Matched on the shared UUID, never on ref/seq, which
// are per-instance. seq is supplied so the items_assign_ref trigger (which
// fires only WHEN NEW.seq IS NULL) assigns this instance's own local ref.
func (q *Queries) UpsertSyncedItem(ctx context.Context, arg UpsertSyncedItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, upsertSyncedItem,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Source,
		arg.ExternalRef,
		arg.Tags,
		arg.Metadata,
		arg.AcceptanceCriteria,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.DeletedAt,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.Source,
		&i.ExternalRef,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Search,
		&i.IdempotencyKey,
		&i.AcceptanceCriteria,
		&i.Seq,
		&i.Ref,
		&i.Version,
		&i.Embedding,
		&i.EmbeddingModel,
	)
	return i, err
}
