// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package store

import (
	"context"
	"time"
)

const actorStats = `-- name: ActorStats :many
SELECT actor,
       count(*)                                                            AS calls,
       count(*) FILTER (WHERE NOT ok)                                      AS errors,
       count(*) FILTER (WHERE tool IN ('get_project_context', 'get_global_context', 'list_projects', 'resolve_project')) AS orient_calls,
       count(*) FILTER (WHERE tool IN ('create_item', 'create_items', 'update_item', 'complete_item', 'log_activity',
                                       'update_project_summary', 'set_project_instructions', 'create_project',
                                       'archive_project', 'link_items', 'unlink_items', 'add_item_ref'))      AS write_calls,
       count(*) FILTER (WHERE tool = 'search')                             AS search_calls,
       (percentile_cont(0.5) WITHIN GROUP (ORDER BY duration_ms))::float8  AS p50_ms,
       COALESCE(avg(result_bytes), 0)::float8                              AS avg_result_bytes,
       min(called_at)::timestamptz                                         AS first_used,
       max(called_at)::timestamptz                                         AS last_used,
       (SELECT array_agg(t ORDER BY c DESC, t)
          FROM (SELECT tool AS t, count(*) AS c FROM tool_calls i
                WHERE i.actor = o.actor AND i.called_at >= $1
                GROUP BY tool ORDER BY c DESC, tool LIMIT 5) top)::text[]  AS top_tools
FROM tool_calls o
WHERE called_at >= $1
GROUP BY actor
ORDER BY calls DESC
`

type ActorStatsRow struct {
	Actor          string    `json:"actor"`
	Calls          int64     `json:"calls"`
	Errors         int64     `json:"errors"`
	OrientCalls    int64     `json:"orient_calls"`
	WriteCalls     int64     `json:"write_calls"`
	SearchCalls    int64     `json:"search_calls"`
	P50Ms          float64   `json:"p50_ms"`
	AvgResultBytes float64   `json:"avg_result_bytes"`
	FirstUsed      time.Time `json:"first_used"`
	LastUsed       time.Time `json:"last_used"`
	TopTools       []string  `json:"top_tools"`
}

// Per-actor behavior over a window. actor is the API key name (OAuth tokens
// inherit it), so this is per-client/per-device usage: how much each caller
// does, how often it orients before writing, what it searches, and whether
// it errs. orient_calls counts the read-side entry points agents are meant
// to start from.
func (q *Queries) ActorStats(ctx context.Context, calledAt time.Time) ([]ActorStatsRow, error) {
	rows, err := q.db.Query(ctx, actorStats, calledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorStatsRow
	for rows.Next() {
		var i ActorStatsRow
		if err := rows.Scan(
			&i.Actor,
			&i.Calls,
			&i.Errors,
			&i.OrientCalls,
			&i.WriteCalls,
			&i.SearchCalls,
			&i.P50Ms,
			&i.AvgResultBytes,
			&i.FirstUsed,
			&i.LastUsed,
			&i.TopTools,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailyToolCalls = `-- name: DailyToolCalls :many
SELECT date_trunc('day', called_at)::timestamptz AS day,
       count(*)                         AS calls,
       count(*) FILTER (WHERE NOT ok)   AS errors
FROM tool_calls
WHERE called_at >= $1
GROUP BY 1
ORDER BY 1
`

type DailyToolCallsRow struct {
	Day    time.Time `json:"day"`
	Calls  int64     `json:"calls"`
	Errors int64     `json:"errors"`
}

func (q *Queries) DailyToolCalls(ctx context.Context, calledAt time.Time) ([]DailyToolCallsRow, error) {
	rows, err := q.db.Query(ctx, dailyToolCalls, calledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyToolCallsRow
	for rows.Next() {
		var i DailyToolCallsRow
		if err := rows.Scan(&i.Day, &i.Calls, &i.Errors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const embeddingCoverage = `-- name: EmbeddingCoverage :one
SELECT
  (SELECT count(*) FROM items WHERE deleted_at IS NULL)                                                       AS items_total,
  (SELECT count(*) FROM items WHERE deleted_at IS NULL AND embedding IS NOT NULL)                             AS items_embedded,
  (SELECT count(*) FROM items WHERE deleted_at IS NULL AND embedding IS NULL AND embedding_model = 'failed')  AS items_failed,
  (SELECT count(*) FROM activity WHERE kind IN ('decision','progress','rejected') AND body <> '')             AS activity_total,
  (SELECT count(*) FROM activity a JOIN activity_embeddings e ON e.activity_id = a.id
     WHERE a.kind IN ('decision','progress','rejected') AND a.body <> '' AND e.embedding IS NOT NULL)         AS activity_embedded
`

type EmbeddingCoverageRow struct {
	ItemsTotal       int64 `json:"items_total"`
	ItemsEmbedded    int64 `json:"items_embedded"`
	ItemsFailed      int64 `json:"items_failed"`
	ActivityTotal    int64 `json:"activity_total"`
	ActivityEmbedded int64 `json:"activity_embedded"`
}

// Semantic-tier backfill health: how many live items are embedded vs poison
// ('failed'), and the same for high-signal activity (the kinds the embedder
// targets). A low embedded fraction means semantic search is starved — no amount
// of distance-threshold tuning helps until the backfill catches up.
func (q *Queries) EmbeddingCoverage(ctx context.Context) (EmbeddingCoverageRow, error) {
	row := q.db.QueryRow(ctx, embeddingCoverage)
	var i EmbeddingCoverageRow
	err := row.Scan(
		&i.ItemsTotal,
		&i.ItemsEmbedded,
		&i.ItemsFailed,
		&i.ActivityTotal,
		&i.ActivityEmbedded,
	)
	return i, err
}

const insertSearchLog = `-- name: InsertSearchLog :exec
INSERT INTO search_log (actor, query, fts_hits, semantic_hits, trigram_hits, activity_hits, returned)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSearchLogParams struct {
	Actor        string `json:"actor"`
	Query        string `json:"query"`
	FtsHits      int32  `json:"fts_hits"`
	SemanticHits int32  `json:"semantic_hits"`
	TrigramHits  int32  `json:"trigram_hits"`
	ActivityHits int32  `json:"activity_hits"`
	Returned     int32  `json:"returned"`
}

func (q *Queries) InsertSearchLog(ctx context.Context, arg InsertSearchLogParams) error {
	_, err := q.db.Exec(ctx, insertSearchLog,
		arg.Actor,
		arg.Query,
		arg.FtsHits,
		arg.SemanticHits,
		arg.TrigramHits,
		arg.ActivityHits,
		arg.Returned,
	)
	return err
}

const insertToolCall = `-- name: InsertToolCall :exec
INSERT INTO tool_calls (tool, actor, project, ok, error, duration_ms, args, result_bytes)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($8::jsonb, '{}'), $7)
`

type InsertToolCallParams struct {
	Tool        string `json:"tool"`
	Actor       string `json:"actor"`
	Project     string `json:"project"`
	Ok          bool   `json:"ok"`
	Error       string `json:"error"`
	DurationMs  int32  `json:"duration_ms"`
	ResultBytes int32  `json:"result_bytes"`
	Args        []byte `json:"args"`
}

func (q *Queries) InsertToolCall(ctx context.Context, arg InsertToolCallParams) error {
	_, err := q.db.Exec(ctx, insertToolCall,
		arg.Tool,
		arg.Actor,
		arg.Project,
		arg.Ok,
		arg.Error,
		arg.DurationMs,
		arg.ResultBytes,
		arg.Args,
	)
	return err
}

const purgeOldSearchLog = `-- name: PurgeOldSearchLog :execrows
DELETE FROM search_log WHERE searched_at < $1
`

func (q *Queries) PurgeOldSearchLog(ctx context.Context, searchedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldSearchLog, searchedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeOldToolCalls = `-- name: PurgeOldToolCalls :execrows
DELETE FROM tool_calls WHERE called_at < $1
`

func (q *Queries) PurgeOldToolCalls(ctx context.Context, calledAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldToolCalls, calledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recentToolErrors = `-- name: RecentToolErrors :many
SELECT tool, error, called_at
FROM tool_calls
WHERE called_at >= $1 AND NOT ok
ORDER BY called_at DESC
LIMIT 10
`

type RecentToolErrorsRow struct {
	Tool     string    `json:"tool"`
	Error    string    `json:"error"`
	CalledAt time.Time `json:"called_at"`
}

func (q *Queries) RecentToolErrors(ctx context.Context, calledAt time.Time) ([]RecentToolErrorsRow, error) {
	rows, err := q.db.Query(ctx, recentToolErrors, calledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentToolErrorsRow
	for rows.Next() {
		var i RecentToolErrorsRow
		if err := rows.Scan(&i.Tool, &i.Error, &i.CalledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentZeroResultSearches = `-- name: RecentZeroResultSearches :many
SELECT query, searched_at
FROM search_log
WHERE searched_at >= $1 AND returned = 0 AND activity_hits = 0
ORDER BY searched_at DESC
LIMIT 10
`

type RecentZeroResultSearchesRow struct {
	Query      string    `json:"query"`
	SearchedAt time.Time `json:"searched_at"`
}

func (q *Queries) RecentZeroResultSearches(ctx context.Context, searchedAt time.Time) ([]RecentZeroResultSearchesRow, error) {
	rows, err := q.db.Query(ctx, recentZeroResultSearches, searchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentZeroResultSearchesRow
	for rows.Next() {
		var i RecentZeroResultSearchesRow
		if err := rows.Scan(&i.Query, &i.SearchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsageSummary = `-- name: SearchUsageSummary :one
SELECT count(*)                                                                          AS searches,
       count(*) FILTER (WHERE returned = 0 AND activity_hits = 0)                        AS zero_result,
       count(*) FILTER (WHERE fts_hits = 0 AND semantic_hits > 0)                        AS semantic_rescues,
       count(*) FILTER (WHERE fts_hits = 0 AND semantic_hits = 0 AND trigram_hits > 0)   AS trigram_rescues,
       COALESCE(avg(returned), 0)::float8                                                AS avg_returned
FROM search_log
WHERE searched_at >= $1
`

type SearchUsageSummaryRow struct {
	Searches        int64   `json:"searches"`
	ZeroResult      int64   `json:"zero_result"`
	SemanticRescues int64   `json:"semantic_rescues"`
	TrigramRescues  int64   `json:"trigram_rescues"`
	AvgReturned     float64 `json:"avg_returned"`
}

// semantic_rescues / trigram_rescues: searches where lexical FTS found nothing
// but a fallback tier did — direct evidence those tiers earn their keep.
func (q *Queries) SearchUsageSummary(ctx context.Context, searchedAt time.Time) (SearchUsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, searchUsageSummary, searchedAt)
	var i SearchUsageSummaryRow
	err := row.Scan(
		&i.Searches,
		&i.ZeroResult,
		&i.SemanticRescues,
		&i.TrigramRescues,
		&i.AvgReturned,
	)
	return i, err
}

const toolCallStats = `-- name: ToolCallStats :many
SELECT tool,
       count(*)                                                            AS calls,
       count(*) FILTER (WHERE NOT ok)                                      AS errors,
       (percentile_cont(0.5)  WITHIN GROUP (ORDER BY duration_ms))::float8 AS p50_ms,
       (percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms))::float8 AS p95_ms,
       COALESCE(avg(result_bytes), 0)::float8                              AS avg_result_bytes,
       max(called_at)::timestamptz                                         AS last_used
FROM tool_calls
WHERE called_at >= $1
GROUP BY tool
ORDER BY calls DESC
`

type ToolCallStatsRow struct {
	Tool           string    `json:"tool"`
	Calls          int64     `json:"calls"`
	Errors         int64     `json:"errors"`
	P50Ms          float64   `json:"p50_ms"`
	P95Ms          float64   `json:"p95_ms"`
	AvgResultBytes float64   `json:"avg_result_bytes"`
	LastUsed       time.Time `json:"last_used"`
}

// Per-tool behavior over a window: volume, error count, latency percentiles,
// and average result size (the token-cost proxy agents pay to call it).
func (q *Queries) ToolCallStats(ctx context.Context, calledAt time.Time) ([]ToolCallStatsRow, error) {
	rows, err := q.db.Query(ctx, toolCallStats, calledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolCallStatsRow
	for rows.Next() {
		var i ToolCallStatsRow
		if err := rows.Scan(
			&i.Tool,
			&i.Calls,
			&i.Errors,
			&i.P50Ms,
			&i.P95Ms,
			&i.AvgResultBytes,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topProjectsByToolCalls = `-- name: TopProjectsByToolCalls :many
SELECT project, count(*) AS calls
FROM tool_calls
WHERE called_at >= $1 AND project <> ''
GROUP BY project
ORDER BY calls DESC
LIMIT 10
`

type TopProjectsByToolCallsRow struct {
	Project string `json:"project"`
	Calls   int64  `json:"calls"`
}

func (q *Queries) TopProjectsByToolCalls(ctx context.Context, calledAt time.Time) ([]TopProjectsByToolCallsRow, error) {
	rows, err := q.db.Query(ctx, topProjectsByToolCalls, calledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopProjectsByToolCallsRow
	for rows.Next() {
		var i TopProjectsByToolCallsRow
		if err := rows.Scan(&i.Project, &i.Calls); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
