// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (project_id, url, secret, events)
VALUES (
    $2,
    $1,
    COALESCE($3::text, ''),
    COALESCE($4::text[], '{}')
)
RETURNING id, project_id, url, secret, events, active, created_at
`

type CreateWebhookParams struct {
	Url       string      `json:"url"`
	ProjectID pgtype.UUID `json:"project_id"`
	Secret    *string     `json:"secret"`
	Events    []string    `json:"events"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.Url,
		arg.ProjectID,
		arg.Secret,
		arg.Events,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const enqueueWebhookEvent = `-- name: EnqueueWebhookEvent :one

INSERT INTO webhook_events (project_id, event, payload)
VALUES ($3, $1, $2)
RETURNING id, project_id, event, payload, attempts, next_attempt_at, delivered_at, last_error, created_at, delivered_hook_ids, parked_at
`

type EnqueueWebhookEventParams struct {
	Event     string          `json:"event"`
	Payload   json.RawMessage `json:"payload"`
	ProjectID pgtype.UUID     `json:"project_id"`
}

// --- durable outbox ---
// Called inside the originating write's transaction (transactional outbox).
func (q *Queries) EnqueueWebhookEvent(ctx context.Context, arg EnqueueWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, enqueueWebhookEvent, arg.Event, arg.Payload, arg.ProjectID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Event,
		&i.Payload,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredHookIds,
		&i.ParkedAt,
	)
	return i, err
}

const leaseWebhookEvents = `-- name: LeaseWebhookEvents :many
UPDATE webhook_events SET next_attempt_at = now() + interval '1 minute'
WHERE id IN (
    SELECT id FROM webhook_events
    WHERE delivered_at IS NULL AND parked_at IS NULL AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    FOR UPDATE SKIP LOCKED
    LIMIT $1::int
)
RETURNING id, project_id, event, payload, attempts, next_attempt_at, delivered_at, last_error, created_at, delivered_hook_ids, parked_at
`

// Atomically claim a batch of due events and push their next attempt into the
// future (a lease), so delivery happens outside the row lock and concurrent
// workers never grab the same event.
func (q *Queries) LeaseWebhookEvents(ctx context.Context, lim int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, leaseWebhookEvents, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEvent
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Event,
			&i.Payload,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredHookIds,
			&i.ParkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWebhooksForEvent = `-- name: ListActiveWebhooksForEvent :many
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks
WHERE active = true
  AND (project_id IS NULL OR project_id = $1)
  AND (cardinality(events) = 0 OR $2::text = ANY(events))
ORDER BY created_at
`

type ListActiveWebhooksForEventParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Event     string      `json:"event"`
}

// Webhooks subscribed to this project (or all projects) and this event (or all).
func (q *Queries) ListActiveWebhooksForEvent(ctx context.Context, arg ListActiveWebhooksForEventParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksForEvent, arg.ProjectID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedWebhookEvents = `-- name: ListFailedWebhookEvents :many
SELECT id, project_id, event, payload, attempts, next_attempt_at, delivered_at, last_error, created_at, delivered_hook_ids, parked_at FROM webhook_events
WHERE last_error <> ''
ORDER BY created_at DESC
LIMIT $1
`

// Dead-lettered / erroring events for operator visibility (last_error set).
func (q *Queries) ListFailedWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listFailedWebhookEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEvent
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Event,
			&i.Payload,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredHookIds,
			&i.ParkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks ORDER BY created_at DESC
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookEventDelivered = `-- name: MarkWebhookEventDelivered :exec
UPDATE webhook_events SET delivered_at = now(), last_error = $2 WHERE id = $1
`

type MarkWebhookEventDeliveredParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

func (q *Queries) MarkWebhookEventDelivered(ctx context.Context, arg MarkWebhookEventDeliveredParams) error {
	_, err := q.db.Exec(ctx, markWebhookEventDelivered, arg.ID, arg.LastError)
	return err
}

const parkWebhookEvent = `-- name: ParkWebhookEvent :exec
UPDATE webhook_events
SET parked_at = now(), last_error = $2, delivered_hook_ids = $3
WHERE id = $1
`

type ParkWebhookEventParams struct {
	ID               uuid.UUID   `json:"id"`
	LastError        string      `json:"last_error"`
	DeliveredHookIds []uuid.UUID `json:"delivered_hook_ids"`
}

// Dead-letter: attempts exhausted. Distinct from delivered_at so the two states
// can't be conflated; the row stays visible for the operator dead-letter view.
func (q *Queries) ParkWebhookEvent(ctx context.Context, arg ParkWebhookEventParams) error {
	_, err := q.db.Exec(ctx, parkWebhookEvent, arg.ID, arg.LastError, arg.DeliveredHookIds)
	return err
}

const purgeDeliveredWebhookEvents = `-- name: PurgeDeliveredWebhookEvents :execrows
DELETE FROM webhook_events WHERE delivered_at IS NOT NULL AND delivered_at < $1
`

func (q *Queries) PurgeDeliveredWebhookEvents(ctx context.Context, deliveredAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeliveredWebhookEvents, deliveredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeParkedWebhookEvents = `-- name: PurgeParkedWebhookEvents :execrows
DELETE FROM webhook_events WHERE parked_at IS NOT NULL AND parked_at < $1
`

func (q *Queries) PurgeParkedWebhookEvents(ctx context.Context, parkedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeParkedWebhookEvents, parkedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleWebhookEvent = `-- name: RescheduleWebhookEvent :exec
UPDATE webhook_events
SET attempts = attempts + 1, next_attempt_at = $2, last_error = $3,
    delivered_hook_ids = $4
WHERE id = $1
`

type RescheduleWebhookEventParams struct {
	ID               uuid.UUID   `json:"id"`
	NextAttemptAt    time.Time   `json:"next_attempt_at"`
	LastError        string      `json:"last_error"`
	DeliveredHookIds []uuid.UUID `json:"delivered_hook_ids"`
}

// delivered_hook_ids records the subscribers that already ACKed this event, so
// the retry only re-POSTs to the ones still failing (no duplicate deliveries).
func (q *Queries) RescheduleWebhookEvent(ctx context.Context, arg RescheduleWebhookEventParams) error {
	_, err := q.db.Exec(ctx, rescheduleWebhookEvent,
		arg.ID,
		arg.NextAttemptAt,
		arg.LastError,
		arg.DeliveredHookIds,
	)
	return err
}
