// Package sync implements cross-instance project sharing: two flightdeck
// instances keeping one project in step by exchanging encrypted messages
// through a mailbox neither can reach directly.
//
// Both sides may write. This is a shared project, not a read-only mirror, so
// every message is a change either end might have made.
//
// Sync identity is items.id / activity.id. Those are already UUIDs, so a row
// carries the same identity everywhere and matching needs no new columns. It
// deliberately is NOT seq/ref: both instances create items, and their
// per-project sequences would collide immediately. Each instance assigns its
// own local ref, so the same item can be flightdeck-12 here and flightdeck-31
// there.
package sync

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"golang.org/x/crypto/chacha20poly1305"
)

// ProtocolVersion is carried in every envelope. Instances update
// independently, so a peer must be able to recognise and refuse a message it
// does not understand rather than misinterpret it.
const ProtocolVersion = 1

// Message kinds.
const (
	KindItem     = "item"
	KindActivity = "activity"
	KindProject  = "project"
)

// Envelope is the plaintext structure that gets sealed. The mailbox host sees
// only the ciphertext.
type Envelope struct {
	Version int             `json:"v"`
	Kind    string          `json:"kind"`
	Origin  string          `json:"origin"` // instance id that produced the change
	SentAt  time.Time       `json:"sent_at"`
	Payload json.RawMessage `json:"payload"`
}

// ItemPayload is one item's syncable state.
//
// Excluded on purpose: project_id and seq/ref (per-instance), search tsvector
// (generated by Postgres), embedding (regenerated locally, and instances may
// use different models), version and position (local concurrency and board
// ordering), idempotency_key (the publisher's agent chose it; it would be
// meaningless and possibly colliding here).
//
// updated_at is excluded too, and that one is load-bearing. A BEFORE UPDATE
// trigger sets it to now() on every write, so an applied row can never carry
// the sender's value. Including it would make the two instances hash the same
// logical content differently and volley the row back and forth forever.
// created_at is safe by contrast: the trigger only touches updated_at.
type ItemPayload struct {
	ID                 string          `json:"id"`
	Type               string          `json:"type"`
	Title              string          `json:"title"`
	Body               string          `json:"body"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	Assignee           *string         `json:"assignee,omitempty"`
	ExternalRef        *string         `json:"external_ref,omitempty"`
	Tags               []string        `json:"tags,omitempty"`
	Metadata           json.RawMessage `json:"metadata,omitempty"`
	AcceptanceCriteria json.RawMessage `json:"acceptance_criteria,omitempty"`
	CreatedAt          time.Time       `json:"created_at"`
	ClosedAt           *time.Time      `json:"closed_at,omitempty"`
	DeletedAt          *time.Time      `json:"deleted_at,omitempty"`
}

// ActivityPayload is one activity row. Append-only by nature, so it never
// conflicts — the two sides simply take the union.
type ActivityPayload struct {
	ID         string          `json:"id"`
	ItemID     *string         `json:"item_id,omitempty"`
	Kind       string          `json:"kind"`
	Actor      string          `json:"actor"`
	Body       string          `json:"body"`
	Confidence *string         `json:"confidence,omitempty"`
	Metadata   json.RawMessage `json:"metadata,omitempty"`
	CreatedAt  time.Time       `json:"created_at"`
}

// ProjectPayload carries the project's own descriptive state. Slug is excluded:
// each instance names the project locally, and a slug is globally unique here.
// updated_at is excluded for the same reason as on items — see ItemPayload.
type ProjectPayload struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Summary      string `json:"summary"`
	Instructions string `json:"instructions"`
}

// ContentHash fingerprints a payload so the sync loop can tell a real change
// from a row it has already exchanged. This is what stops an applied message
// from looking like a local edit and echoing straight back to the peer.
func ContentHash(v any) (string, error) {
	// json.Marshal orders struct fields by declaration, so the same value
	// always produces the same bytes here.
	b, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:]), nil
}

// Seal encrypts an envelope with the share's symmetric key.
//
// XChaCha20-Poly1305 with a random nonce: the 192-bit nonce makes random
// generation safe for far more messages than this will ever send, avoiding the
// counter coordination a 96-bit nonce would need between two instances that
// cannot see each other's state.
func Seal(key []byte, env Envelope) ([]byte, error) {
	plaintext, err := json.Marshal(env)
	if err != nil {
		return nil, err
	}
	aead, err := chacha20poly1305.NewX(key)
	if err != nil {
		return nil, fmt.Errorf("cipher: %w", err)
	}
	nonce := make([]byte, aead.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, err
	}
	// Nonce is prepended, then the ciphertext with its authentication tag.
	return aead.Seal(nonce, nonce, plaintext, nil), nil
}

// Open decrypts and validates an envelope. A wrong key, a truncated message, or
// any tampering fails here rather than producing garbage that gets applied.
func Open(key []byte, sealed []byte) (Envelope, error) {
	var env Envelope
	aead, err := chacha20poly1305.NewX(key)
	if err != nil {
		return env, fmt.Errorf("cipher: %w", err)
	}
	if len(sealed) < aead.NonceSize() {
		return env, errors.New("message too short to contain a nonce")
	}
	nonce, ct := sealed[:aead.NonceSize()], sealed[aead.NonceSize():]
	plaintext, err := aead.Open(nil, nonce, ct, nil)
	if err != nil {
		return env, fmt.Errorf("decrypt: %w", err)
	}
	if err := json.Unmarshal(plaintext, &env); err != nil {
		return env, fmt.Errorf("decode envelope: %w", err)
	}
	if env.Version != ProtocolVersion {
		return env, fmt.Errorf("unsupported protocol version %d (this instance speaks %d)", env.Version, ProtocolVersion)
	}
	return env, nil
}

// NewKey mints a share's symmetric key.
func NewKey() ([]byte, error) {
	k := make([]byte, chacha20poly1305.KeySize)
	_, err := rand.Read(k)
	return k, err
}

// Invite is the whole handshake, reduced to one paste-able string.
//
// It carries everything the other instance needs and nothing it can get
// elsewhere: where the mailbox is, the certificate bundle to get through the
// door at all, which mailboxes to use in each direction, and the symmetric key
// the mailbox host must never see. Anyone holding this can read and write the
// shared project, so it travels out of band and is revoked by deleting the
// mailboxes.
type Invite struct {
	Version     int    `json:"v"`
	PeerName    string `json:"peer"`
	ProjectSlug string `json:"slug"`
	ProjectName string `json:"name"`
	MailboxURL  string `json:"url"`

	// Direction is from the joiner's point of view: they send to SendMailbox
	// and drain RecvMailbox. The creator holds the mirror image, so one invite
	// configures both ends of a bidirectional link.
	SendMailbox string `json:"send_mb"`
	SendToken   string `json:"send_tok"`
	RecvMailbox string `json:"recv_mb"`
	RecvToken   string `json:"recv_tok"`

	Secret     []byte `json:"secret"`
	ClientCert string `json:"cert"`
	ClientKey  string `json:"key"`
	CAPEM      string `json:"ca"`
}

// Encode renders an invite as a single opaque token safe to paste into a chat
// or a terminal.
func (i Invite) Encode() (string, error) {
	b, err := json.Marshal(i)
	if err != nil {
		return "", err
	}
	return "fdshare_" + base64.RawURLEncoding.EncodeToString(b), nil
}

// DecodeInvite parses a pasted invite code.
func DecodeInvite(code string) (Invite, error) {
	var inv Invite
	const prefix = "fdshare_"
	if len(code) <= len(prefix) || code[:len(prefix)] != prefix {
		return inv, errors.New("not a flightdeck invite code (expected an fdshare_ prefix)")
	}
	b, err := base64.RawURLEncoding.DecodeString(code[len(prefix):])
	if err != nil {
		return inv, fmt.Errorf("invite code is malformed: %w", err)
	}
	if err := json.Unmarshal(b, &inv); err != nil {
		return inv, fmt.Errorf("invite code is malformed: %w", err)
	}
	if inv.Version != ProtocolVersion {
		return inv, fmt.Errorf("invite uses protocol version %d, this instance speaks %d", inv.Version, ProtocolVersion)
	}
	if len(inv.Secret) != chacha20poly1305.KeySize {
		return inv, errors.New("invite is missing its encryption key")
	}
	if inv.MailboxURL == "" || inv.SendMailbox == "" || inv.RecvMailbox == "" {
		return inv, errors.New("invite is missing mailbox details")
	}
	return inv, nil
}
